In [1]:
import pandas as pd
import numpy as np

In [2]:
# Current GTFS edited (T2 and Metro lines removed)

shapes = pd.read_csv('./output/current_edited/shapes.txt')
routes = pd.read_csv('./output/current_edited/routes.txt')
trips = pd.read_csv('./output/current_edited/trips.txt')
stoptimes = pd.read_csv('./output/current_edited/stop_times.txt')
calendar = pd.read_csv('./output/current_edited/calendar.txt')
calendardates = pd.read_csv('./output/current_edited/calendar_dates.txt')
stops = pd.read_csv('./output/current_edited/stops.txt')

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0,3,5,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Check route 801 going to WS Airport

In [7]:
shapes.loc[shapes['shape_id'].str.contains('22-801')]['shape_id'].unique()

array(['22-801-sj2-1.1.R', '22-801-sj2-1.2.H', '22-801-sj2-1.3.H',
       '22-801-sj2-1.4.H', '22-801-sj2-1.5.R', '22-801-sj2-1.6.R'],
      dtype=object)

In [8]:
routes.loc[routes['route_id'].str.contains('22-801')]['route_id'].unique()

array(['22-801-sj2-1'], dtype=object)

In [14]:
routeid801 = '22-801-sj2-1'

In [15]:
trips.loc[trips['route_id']==routeid801]

,route_id,service_id,trip_id,shape_id,trip_headsign,direction_id,block_id,wheelchair_accessible,route_direction,trip_note,bikes_allowed
50679,22-801-sj2-1,TA+r1018+5,1141440,22-801-sj2-1.3.H,Badgerys Creek,0,NaN,1,Liverpool to Badgerys Creek,x000x,NaN
51164,22-801-sj2-1,TA+r1028+5,1141387,22-801-sj2-1.1.R,Liverpool,1,NaN,1,Badgerys Creek to Liverpool,NaN,NaN
51165,22-801-sj2-1,TA+r1028+5,1141390,22-801-sj2-1.2.H,Badgerys Creek,0,NaN,1,Liverpool to Badgerys Creek,NaN,NaN
51166,22-801-sj2-1,TA+r1028+5,1141393,22-801-sj2-1.4.H,Badgerys Creek,0,NaN,1,Liverpool to Badgerys Creek,NaN,NaN
51167,22-801-sj2-1,TA+r1028+5,1141385,22-801-sj2-1.5.R,Liverpool,1,NaN,1,Badgerys Creek to Liverpool,NaN,NaN
51168,22-801-sj2-1,TA+r1028+5,1141392,22-801-sj2-1.6.R,Liverpool,1,NaN,1,Badgerys Creek to Liverpool,NaN,NaN
52365,22-801-sj2-1,TA+r1052+5,1160417,22-801-sj2-1.4.H,Badgerys Creek,0,NaN,1,Liverpool to Badgerys Creek,NaN,NaN

In [16]:
tripids801 = trips.loc[trips['route_id']==routeid801]['trip_id'].tolist()
tripids801

['1141440', '1141387', '1141390', '1141393', '1141385', '1141392', '1160417']

In [23]:
stoptimes['trip_id'] = stoptimes['trip_id'].astype(str)
stoptimes.loc[stoptimes['trip_id'].isin(tripids801)]

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
1053223,1141387,08:45:00,08:45:00,255516,1,NaN,0,0,0.00,1,NaN
1053224,1141387,08:46:00,08:46:00,217184,2,NaN,0,0,499.80,0,NaN
1053225,1141387,08:48:00,08:48:00,2171317,3,NaN,0,0,1727.82,0,NaN
1053226,1141387,08:49:00,08:49:00,217185,4,NaN,0,0,2088.91,0,NaN
1053227,1141387,08:54:00,08:54:00,217187,5,NaN,0,0,5399.96,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1053589,1141392,08:30:00,08:30:00,2170170,60,NaN,0,0,32717.95,0,NaN
1053590,1141392,08:33:00,08:33:00,2170231,61,NaN,0,0,33565.47,0,NaN
1053591,1141392,08:34:00,08:34:00,2170232,62,NaN,0,0,33814.88,1,NaN
1053592,1141392,08:36:00,08:36:00,2170243,63,NaN,0,0,34291.93,0,NaN
1053593,1141392,08:39:00,08:39:00,2170805,64,NaN,0,0,34766.31,1,NaN

In [19]:
stopidstoremove = ['217182','217184','255516','25551']

In [20]:
stops.loc[stops['stop_id'].isin(stopidstoremove)]

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,platform_code
37080,217182,217182.0,Badgerys Creek Rd After Elizabeth Dr,-33.876201,150.749499,NaN,NaN,0,NaN
37082,217184,217184.0,Badgerys Creek Rd At Elizabeth Dr,-33.876072,150.748985,NaN,NaN,0,NaN
39609,25551,25551.0,"Badgerys Creek Public School, Badgerys Creek Rd",-33.879734,150.746207,NaN,NaN,0,NaN
39908,255516,255516.0,Badgerys Creek Airport Terminus,-33.879622,150.745770,NaN,NaN,0,NaN

In [34]:
stoptimes['stop_id'] = stoptimes['stop_id'].astype(str)
stoptimes.loc[stoptimes['stop_id'].isin(stopidstoremove)]

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
1053223,1141387,08:45:00,08:45:00,255516,1,NaN,0,0,0.00,1,NaN
1053224,1141387,08:46:00,08:46:00,217184,2,NaN,0,0,499.80,0,NaN
1053332,1141390,17:12:00,17:12:00,217182,60,NaN,0,0,33949.39,0,NaN
1053333,1141390,17:15:00,17:15:00,255516,61,NaN,0,0,35133.99,1,NaN
1053387,1141440,16:24:00,16:24:00,217182,54,NaN,0,0,38642.95,0,NaN
1053388,1141440,16:25:00,16:25:00,25551,55,NaN,0,0,39142.15,0,NaN
1053389,1141440,16:27:00,16:27:00,255516,56,NaN,0,0,40142.81,1,NaN
1053435,1141393,18:55:00,18:55:00,217182,46,NaN,0,0,29574.52,0,NaN
1053436,1141393,18:58:00,18:58:00,255516,47,NaN,0,0,30759.12,1,NaN
1053482,1160417,16:03:00,16:03:00,217182,46,NaN,0,0,29574.52,0,NaN
1053483,1160417,16:06:00,16:06:00,255516,47,NaN,0,0,30759.12,1,NaN
1053484,1141385,16:32:00,16:32:00,255516,1,NaN,0,0,0.00,1,NaN
1053485,1141385,16:33:00,16:33:00,217184,2,NaN,0,0,499.80,0,NaN
1053530,1141392,07:15:00,07:15:00,255516,1,NaN,0,0,0.00,1,NaN
1053531,1141392,07:16:00,07:16:00,217184,2,NaN,0,0,499.80,0,NaN

In [35]:
len(stoptimes.loc[stoptimes['stop_id'].isin(stopidstoremove)])

15

In [ ]:
set(stoptimes.loc[stoptimes['stop_id'].isin(stopidstoremove)]['trip_id'].unique().tolist()) == set(tripids801)

So, these stops are being used only for trips on route 22-801. Removing them will not affect any other routes.

### Remove stops on Badgerys Creek Road

In [30]:
stopidstoremove

['217182', '217184', '255516', '25551']

In [31]:
tripids801

['1141440', '1141387', '1141390', '1141393', '1141385', '1141392', '1160417']

In [32]:
# Remove stops from stops

print(len(stops))
stops = stops.loc[stops['stop_id'].isin(stopidstoremove)==False]
print(len(stops))

44825
44821

In [37]:
# Remove stops from stop_times

print(len(stoptimes))
stoptimes = stoptimes.loc[stoptimes['stop_id'].isin(stopidstoremove)==False]
print(len(stoptimes))

4332661
4332646

In [43]:
# Adjust stop sequence of corresponding trips

stoptimes_trips801 = stoptimes.loc[stoptimes['trip_id'].isin(tripids801)]
len(stoptimes_trips801)

356

In [45]:
stoptimes_trips801['stop_sequence'] = stoptimes_trips801.groupby('trip_id')['shape_dist_traveled'].rank(ascending=True).astype(int)
stoptimes_trips801

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
1053225,1141387,08:48:00,08:48:00,2171317,1,NaN,0,0,1727.82,0,NaN
1053226,1141387,08:49:00,08:49:00,217185,2,NaN,0,0,2088.91,0,NaN
1053227,1141387,08:54:00,08:54:00,217187,3,NaN,0,0,5399.96,0,NaN
1053228,1141387,08:58:00,08:58:00,217188,4,NaN,0,0,7642.53,1,NaN
1053229,1141387,09:00:00,09:00:00,217189,5,NaN,0,0,8275.70,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1053589,1141392,08:30:00,08:30:00,2170170,58,NaN,0,0,32717.95,0,NaN
1053590,1141392,08:33:00,08:33:00,2170231,59,NaN,0,0,33565.47,0,NaN
1053591,1141392,08:34:00,08:34:00,2170232,60,NaN,0,0,33814.88,1,NaN
1053592,1141392,08:36:00,08:36:00,2170243,61,NaN,0,0,34291.93,0,NaN
1053593,1141392,08:39:00,08:39:00,2170805,62,NaN,0,0,34766.31,1,NaN

In [46]:
print(len(stoptimes))
stoptimes = stoptimes.loc[stoptimes['trip_id'].isin(tripids801)==False]
print(len(stoptimes))

4332646
4332290

In [48]:
stoptimes = stoptimes.append(stoptimes_trips801)

In [50]:
stoptimes.loc[stoptimes['stop_id'].isin(stopidstoremove)]

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, timepoint, stop_note]
Index: []

In [49]:
stoptimes.loc[stoptimes['trip_id'].isin(tripids801)]

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,stop_note
1053225,1141387,08:48:00,08:48:00,2171317,1,NaN,0,0,1727.82,0,NaN
1053226,1141387,08:49:00,08:49:00,217185,2,NaN,0,0,2088.91,0,NaN
1053227,1141387,08:54:00,08:54:00,217187,3,NaN,0,0,5399.96,0,NaN
1053228,1141387,08:58:00,08:58:00,217188,4,NaN,0,0,7642.53,1,NaN
1053229,1141387,09:00:00,09:00:00,217189,5,NaN,0,0,8275.70,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1053589,1141392,08:30:00,08:30:00,2170170,58,NaN,0,0,32717.95,0,NaN
1053590,1141392,08:33:00,08:33:00,2170231,59,NaN,0,0,33565.47,0,NaN
1053591,1141392,08:34:00,08:34:00,2170232,60,NaN,0,0,33814.88,1,NaN
1053592,1141392,08:36:00,08:36:00,2170243,61,NaN,0,0,34291.93,0,NaN
1053593,1141392,08:39:00,08:39:00,2170805,62,NaN,0,0,34766.31,1,NaN

In [51]:
# Save stops and stoptimes

stops.to_csv('./output/current_edited/stops.txt', index=False)
stoptimes.to_csv('./output/current_edited/stop_times.txt', index=False)