In [1]:
import pandas as pd
import numpy as np
import geo.sphere

In [2]:
routeshapes = pd.read_csv('./Shapes/FutureTwayLocalRouteShapes_1TOD.csv')
fastshapes_austral = pd.read_csv('./Shapes/allShapes_Austral.csv')
#fastshapes = pd.read_csv('./Shapes/allShapes_FAST.csv')
mgshapes = pd.read_csv('./Shapes/MiddletonGrangeRouteShapes.csv')

In [3]:
routeshapes.head()

,name,vertex_index,vertex_part,vertex_part_index,distance,angle,shape_pt_lat,shape_pt_lon
0,FAST_Aerotropolis,0,0,0,0.000000,277.880043,-33.920722,150.828773
1,FAST_Aerotropolis,1,0,1,0.000895,277.880305,-33.920600,150.827887
2,FAST_Aerotropolis,2,0,2,0.002211,277.880827,-33.920419,150.826583
3,FAST_Aerotropolis,3,0,3,0.003093,277.881248,-33.920298,150.825709
4,FAST_Aerotropolis,4,0,4,0.003563,277.886273,-33.920234,150.825244

In [4]:
(routeshapes['vertex_index']-routeshapes['vertex_part_index']).sum()

0

In [5]:
routeshapes = routeshapes[['name','shape_pt_lat','shape_pt_lon','vertex_index']]
routeshapes.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence']
routeshapes.head()

            shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0  FAST_Aerotropolis    -33.920722    150.828773                  0
1  FAST_Aerotropolis    -33.920600    150.827887                  1
2  FAST_Aerotropolis    -33.920419    150.826583                  2
3  FAST_Aerotropolis    -33.920298    150.825709                  3
4  FAST_Aerotropolis    -33.920234    150.825244                  4

In [6]:
fastshapes_austral.head()

,shape_pt_node,shape_pt_seq,route_id,index,y,x,osmid,highway,ref,lon,lat,geometry
0,272854963,1,TT-2056,272854963,-3.755550e+06,308363.292535,272854963,traffic_signals,NaN,150.926880,-33.922966,POINT (308363.2925353871 -3755550.023884408)
1,5752114846,2,TT-2056,5752114846,-3.755530e+06,308223.643670,5752114846,NaN,NaN,150.925374,-33.922761,POINT (308223.6436695384 -3755530.123583576)
2,272854964,3,TT-2056,272854964,-3.755526e+06,308190.929394,272854964,NaN,NaN,150.925022,-33.922714,POINT (308190.9293939819 -3755525.55927458)
3,1844215663,4,TT-2056,1844215663,-3.755524e+06,308179.713530,1844215663,traffic_signals,NaN,150.924901,-33.922697,POINT (308179.7135300513 -3755523.899919145)
4,274485396,5,TT-2056,274485396,-3.755509e+06,308070.652350,274485396,NaN,NaN,150.923725,-33.922544,POINT (308070.6523504682 -3755509.097269811)

In [7]:
fastshapes_austral = fastshapes_austral[['route_id','lat','lon','shape_pt_seq']]
fastshapes_austral.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence']
fastshapes_austral['shape_id'] = fastshapes_austral['shape_id'].apply(lambda x: x+'-austral')
fastshapes_austral.head()

          shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0  TT-2056-austral    -33.922966    150.926880                  1
1  TT-2056-austral    -33.922761    150.925374                  2
2  TT-2056-austral    -33.922714    150.925022                  3
3  TT-2056-austral    -33.922697    150.924901                  4
4  TT-2056-austral    -33.922544    150.923725                  5

In [8]:
mgshapes.head()

,name,vertex_index,vertex_part,vertex_part_index,distance,angle,shape_pt_lat,shape_pt_lon
0,Liverpool-MG,0,0,0,0.000000,277.746654,-33.922966,150.926880
1,Liverpool-MG,1,0,1,0.001519,277.727293,-33.922761,150.925374
2,Liverpool-MG,2,0,2,0.001997,277.567795,-33.922697,150.924901
3,Liverpool-MG,3,0,3,0.003183,234.275974,-33.922544,150.923725
4,Liverpool-MG,4,0,4,0.005102,191.636691,-33.924427,150.923354

In [9]:
mgshapes['name'].unique()

array(['Liverpool-MG', 'MG-Miller-Cartwright-Liverpool',
       'Liverpool-Cartwright-Miller-MG', 'MG-Liverpool',
       'MG-EdmondsonPark', 'EdmondsonPark-MG', 'MG-WetherillPark',
       'WetherillPark-MG', 'MG-Austral_FAST', 'Austral-MG_FAST',
       'FAST_MG_TOD', 'MG_FAST_TOD'], dtype=object)

In [10]:
# Get the route to west, others can directly be added to GTFS while combining with rail and current GTFS

mgshapes = mgshapes.loc[mgshapes['name'].str.contains('TOD')].reset_index(drop=True)
print((mgshapes['vertex_index']-mgshapes['vertex_part_index']).sum())
mgshapes = mgshapes[['name','shape_pt_lat','shape_pt_lon','vertex_index']]
mgshapes.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence']
mgshapes.head()

0

      shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0  FAST_MG_TOD    -33.920722    150.828773                  0
1  FAST_MG_TOD    -33.920741    150.828907                  1
2  FAST_MG_TOD    -33.920803    150.829307                  2
3  FAST_MG_TOD    -33.920831    150.829500                  3
4  FAST_MG_TOD    -33.920866    150.829742                  4

In [11]:
mgshapes['shape_id'].unique()

array(['FAST_MG_TOD', 'MG_FAST_TOD'], dtype=object)

In [12]:
print(len(routeshapes))
print(len(fastshapes_austral))
print(len(mgshapes))
routeshapes = routeshapes.append(fastshapes_austral, ignore_index=True).append(mgshapes, ignore_index=True)
print(len(routeshapes))

7589
420
141
8150

### Tways

In [13]:
# 15th Avenue (Liverpool - Aerotropolis)

tway15th_lvpl_aero = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
tway15th_lvpl_aero = tway15th_lvpl_aero.append(routeshapes.loc[routeshapes['shape_id']=='FAST_Aerotropolis'].sort_values('shape_pt_sequence'))
tway15th_lvpl_aero = tway15th_lvpl_aero.reset_index(drop=True)
tway15th_lvpl_aero['shape_pt_sequence'] = tway15th_lvpl_aero.index+1
tway15th_lvpl_aero['shape_id'] = '15th-LVPL-AERO'

tway15th_aero_lvpl = routeshapes.loc[routeshapes['shape_id']=='Aerotropolis_FAST'].sort_values('shape_pt_sequence')
tway15th_aero_lvpl = tway15th_aero_lvpl.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
tway15th_aero_lvpl = tway15th_aero_lvpl.reset_index(drop=True)
tway15th_aero_lvpl['shape_pt_sequence'] = tway15th_aero_lvpl.index+1
tway15th_aero_lvpl['shape_id'] = '15th-AERO-LVPL'

tway15th = tway15th_lvpl_aero.append(tway15th_aero_lvpl, ignore_index=True)
tway15th

           shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    15th-LVPL-AERO    -33.922966    150.926880                  1
1    15th-LVPL-AERO    -33.922761    150.925374                  2
2    15th-LVPL-AERO    -33.922714    150.925022                  3
3    15th-LVPL-AERO    -33.922697    150.924901                  4
4    15th-LVPL-AERO    -33.922544    150.923725                  5
..              ...           ...           ...                ...
652  15th-AERO-LVPL    -33.924286    150.926628                314
653  15th-AERO-LVPL    -33.923973    150.926684                315
654  15th-AERO-LVPL    -33.923700    150.926733                316
655  15th-AERO-LVPL    -33.923661    150.926740                317
656  15th-AERO-LVPL    -33.922966    150.926880                318

[657 rows x 4 columns]

In [14]:
# 10th Avenue (Casula - Aerotropolis South)

tway10th_csla_asth = routeshapes.loc[routeshapes['shape_id']=='10thAv-Casula-Aerotropolis'].sort_values('shape_pt_sequence')
tway10th_csla_asth = tway10th_csla_asth.reset_index(drop=True)
tway10th_csla_asth['shape_pt_sequence'] = tway10th_csla_asth.index+1
tway10th_csla_asth['shape_id'] = '10th-CSLA-ASTH'

tway10th_asth_csla = routeshapes.loc[routeshapes['shape_id']=='10thAv-Aerotropolis-Casula'].sort_values('shape_pt_sequence')
tway10th_asth_csla = tway10th_asth_csla.reset_index(drop=True)
tway10th_asth_csla['shape_pt_sequence'] = tway10th_asth_csla.index+1
tway10th_asth_csla['shape_id'] = '10th-ASTH-CSLA'

tway10th = tway10th_csla_asth.append(tway10th_asth_csla, ignore_index=True)
tway10th

           shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    10th-CSLA-ASTH    -33.949904    150.911435                  1
1    10th-CSLA-ASTH    -33.950275    150.911325                  2
2    10th-CSLA-ASTH    -33.950353    150.911280                  3
3    10th-CSLA-ASTH    -33.950489    150.911095                  4
4    10th-CSLA-ASTH    -33.950565    150.911058                  5
..              ...           ...           ...                ...
874  10th-ASTH-CSLA    -33.950565    150.911058                423
875  10th-ASTH-CSLA    -33.950489    150.911095                424
876  10th-ASTH-CSLA    -33.950353    150.911280                425
877  10th-ASTH-CSLA    -33.950275    150.911325                426
878  10th-ASTH-CSLA    -33.949904    150.911435                427

[879 rows x 4 columns]

In [15]:
# 20th Avenue (Liverpool - Aerotropolis)

tway20th_lvpl_aero = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
tway20th_lvpl_aero = tway20th_lvpl_aero.append(routeshapes.loc[routeshapes['shape_id']=='20thAv_FAST_BadgerysCreek'].sort_values('shape_pt_sequence'))
tway20th_lvpl_aero = tway20th_lvpl_aero.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-BadgerysCreek-Aerotropolis'].sort_values('shape_pt_sequence'))
tway20th_lvpl_aero = tway20th_lvpl_aero.reset_index(drop=True)
tway20th_lvpl_aero['shape_pt_sequence'] = tway20th_lvpl_aero.index+1
tway20th_lvpl_aero['shape_id'] = '20th-LVPL-AERO'

tway20th_aero_lvpl = routeshapes.loc[routeshapes['shape_id']=='20thAv-Aerotropolis-BadgerysCreek'].sort_values('shape_pt_sequence')
tway20th_aero_lvpl = tway20th_aero_lvpl.append(routeshapes.loc[routeshapes['shape_id']=='20thAv_BadgerysCreek_FAST'].sort_values('shape_pt_sequence'))
tway20th_aero_lvpl = tway20th_aero_lvpl.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
tway20th_aero_lvpl = tway20th_aero_lvpl.reset_index(drop=True)
tway20th_aero_lvpl['shape_pt_sequence'] = tway20th_aero_lvpl.index+1
tway20th_aero_lvpl['shape_id'] = '20th-AERO-LVPL'

tway20th = tway20th_lvpl_aero.append(tway20th_aero_lvpl, ignore_index=True)
tway20th

           shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    20th-LVPL-AERO    -33.922966    150.926880                  1
1    20th-LVPL-AERO    -33.922761    150.925374                  2
2    20th-LVPL-AERO    -33.922714    150.925022                  3
3    20th-LVPL-AERO    -33.922697    150.924901                  4
4    20th-LVPL-AERO    -33.922544    150.923725                  5
..              ...           ...           ...                ...
643  20th-AERO-LVPL    -33.924286    150.926628                317
644  20th-AERO-LVPL    -33.923973    150.926684                318
645  20th-AERO-LVPL    -33.923700    150.926733                319
646  20th-AERO-LVPL    -33.923661    150.926740                320
647  20th-AERO-LVPL    -33.922966    150.926880                321

[648 rows x 4 columns]

In [16]:
# 25th Avenue (Cabramatta - Business Park)

tway25th_cbmt_bprk = routeshapes.loc[routeshapes['shape_id']=='25thAv-Cabramatta-ElizabethDrive'].sort_values('shape_pt_sequence')
tway25th_cbmt_bprk = tway25th_cbmt_bprk.append(routeshapes.loc[routeshapes['shape_id']=='25thAv-ElizabethDrive-BusinessPark'].sort_values('shape_pt_sequence'))
tway25th_cbmt_bprk = tway25th_cbmt_bprk.reset_index(drop=True)
tway25th_cbmt_bprk['shape_pt_sequence'] = tway25th_cbmt_bprk.index+1
tway25th_cbmt_bprk['shape_id'] = '25th-CBMT-BPRK'

tway25th_bprk_cbmt = routeshapes.loc[routeshapes['shape_id']=='25thAv-BusinessPark-ElizabethDrive'].sort_values('shape_pt_sequence')
tway25th_bprk_cbmt = tway25th_bprk_cbmt.append(routeshapes.loc[routeshapes['shape_id']=='25thAv-ElizabethDrive-Cabramatta'].sort_values('shape_pt_sequence'))
tway25th_bprk_cbmt = tway25th_bprk_cbmt.reset_index(drop=True)
tway25th_bprk_cbmt['shape_pt_sequence'] = tway25th_bprk_cbmt.index+1
tway25th_bprk_cbmt['shape_id'] = '25th-BPRK-CBMT'

tway25th = tway25th_cbmt_bprk.append(tway25th_bprk_cbmt, ignore_index=True)
tway25th

           shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    25th-CBMT-BPRK    -33.894940    150.938522                  1
1    25th-CBMT-BPRK    -33.895173    150.938475                  2
2    25th-CBMT-BPRK    -33.895390    150.938434                  3
3    25th-CBMT-BPRK    -33.895391    150.938327                  4
4    25th-CBMT-BPRK    -33.895336    150.937808                  5
..              ...           ...           ...                ...
658  25th-BPRK-CBMT    -33.895575    150.937789                321
659  25th-BPRK-CBMT    -33.895543    150.937969                322
660  25th-BPRK-CBMT    -33.895474    150.938418                323
661  25th-BPRK-CBMT    -33.895390    150.938434                324
662  25th-BPRK-CBMT    -33.894940    150.938522                325

[663 rows x 4 columns]

In [17]:
# E road (Leppington - Business Park)

twayE_lptn_bprk = routeshapes.loc[routeshapes['shape_id']=='E-Tway-FromLeppington'].sort_values('shape_pt_sequence')
twayE_lptn_bprk = twayE_lptn_bprk.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-Austral-BadgerysCreek'].sort_values('shape_pt_sequence'))
twayE_lptn_bprk = twayE_lptn_bprk.append(routeshapes.loc[routeshapes['shape_id']=='E-Tway-BadgerysCreek-BusinessPark'].sort_values('shape_pt_sequence'))
twayE_lptn_bprk = twayE_lptn_bprk.reset_index(drop=True)
twayE_lptn_bprk['shape_pt_sequence'] = twayE_lptn_bprk.index+1
twayE_lptn_bprk['shape_id'] = 'E-LPTN-BPRK'

twayE_bprk_lptn = routeshapes.loc[routeshapes['shape_id']=='E-Tway-BusinessPark-BadgerysCreek'].sort_values('shape_pt_sequence')
twayE_bprk_lptn = twayE_bprk_lptn.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-BadgerysCreek-Austral'].sort_values('shape_pt_sequence'))
twayE_bprk_lptn = twayE_bprk_lptn.append(routeshapes.loc[routeshapes['shape_id']=='E-Tway-ToLeppington'].sort_values('shape_pt_sequence'))
twayE_bprk_lptn = twayE_bprk_lptn.reset_index(drop=True)
twayE_bprk_lptn['shape_pt_sequence'] = twayE_bprk_lptn.index+1
twayE_bprk_lptn['shape_id'] = 'E-BPRK-LPTN'

twayE = twayE_lptn_bprk.append(twayE_bprk_lptn, ignore_index=True)
twayE

        shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    E-LPTN-BPRK    -33.953606    150.808177                  1
1    E-LPTN-BPRK    -33.953663    150.808479                  2
2    E-LPTN-BPRK    -33.953690    150.808637                  3
3    E-LPTN-BPRK    -33.953479    150.809189                  4
4    E-LPTN-BPRK    -33.952367    150.809119                  5
..           ...           ...           ...                ...
267  E-BPRK-LPTN    -33.952367    150.809119                133
268  E-BPRK-LPTN    -33.953479    150.809189                134
269  E-BPRK-LPTN    -33.954062    150.809243                135
270  E-BPRK-LPTN    -33.954084    150.808380                136
271  E-BPRK-LPTN    -33.953979    150.807897                137

[272 rows x 4 columns]

In [18]:
# D road (Rossmore - Mt Druitt)

twayD_rsmr_mtdt = routeshapes.loc[routeshapes['shape_id']=='D-Tway-Rossmore-ElizabethDrive'].sort_values('shape_pt_sequence')
twayD_rsmr_mtdt = twayD_rsmr_mtdt.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToMtDruitt'].sort_values('shape_pt_sequence'))
twayD_rsmr_mtdt = twayD_rsmr_mtdt.reset_index(drop=True)
twayD_rsmr_mtdt['shape_pt_sequence'] = twayD_rsmr_mtdt.index+1
twayD_rsmr_mtdt['shape_id'] = 'D-RSMR-MTDT'

twayD_mtdt_rsmr = routeshapes.loc[routeshapes['shape_id']=='Connection-FromMtDruitt'].sort_values('shape_pt_sequence')
twayD_mtdt_rsmr = twayD_mtdt_rsmr.append(routeshapes.loc[routeshapes['shape_id']=='D-Tway-ElizabethDrive-Rossmore'].sort_values('shape_pt_sequence'))
twayD_mtdt_rsmr = twayD_mtdt_rsmr.reset_index(drop=True)
twayD_mtdt_rsmr['shape_pt_sequence'] = twayD_mtdt_rsmr.index+1
twayD_mtdt_rsmr['shape_id'] = 'D-MTDT-RSMR'

twayD = twayD_rsmr_mtdt.append(twayD_mtdt_rsmr, ignore_index=True)
twayD

        shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    D-RSMR-MTDT    -33.950411    150.780747                  1
1    D-RSMR-MTDT    -33.950605    150.782353                  2
2    D-RSMR-MTDT    -33.947929    150.782818                  3
3    D-RSMR-MTDT    -33.948123    150.784423                  4
4    D-RSMR-MTDT    -33.948047    150.784509                  5
..           ...           ...           ...                ...
491  D-MTDT-RSMR    -33.948047    150.784509                224
492  D-MTDT-RSMR    -33.948123    150.784423                225
493  D-MTDT-RSMR    -33.947929    150.782818                226
494  D-MTDT-RSMR    -33.950605    150.782353                227
495  D-MTDT-RSMR    -33.950411    150.780747                228

[496 rows x 4 columns]

In [19]:
# C Road (South Creek - St Marys)

twayC_stck_stmr = routeshapes.loc[routeshapes['shape_id']=='C-Tway-SouthCreek-ElizabethDrive'].sort_values('shape_pt_sequence')
twayC_stck_stmr = twayC_stck_stmr.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToStMarys'].sort_values('shape_pt_sequence'))
twayC_stck_stmr = twayC_stck_stmr.reset_index(drop=True)
twayC_stck_stmr['shape_pt_sequence'] = twayC_stck_stmr.index+1
twayC_stck_stmr['shape_id'] = 'C-STCK-STMR'

twayC_stmr_stck = routeshapes.loc[routeshapes['shape_id']=='Connection-FromStMarys'].sort_values('shape_pt_sequence')
twayC_stmr_stck = twayC_stmr_stck.append(routeshapes.loc[routeshapes['shape_id']=='C-Tway-ElizabethDrive-SouthCreek'].sort_values('shape_pt_sequence'))
twayC_stmr_stck = twayC_stmr_stck.reset_index(drop=True)
twayC_stmr_stck['shape_pt_sequence'] = twayC_stmr_stck.index+1
twayC_stmr_stck['shape_id'] = 'C-STMR-STCK'

twayC = twayC_stck_stmr.append(twayC_stmr_stck, ignore_index=True)
twayC

        shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    C-STCK-STMR    -33.947502    150.756661                  1
1    C-STCK-STMR    -33.948376    150.763887                  2
2    C-STCK-STMR    -33.945699    150.764352                  3
3    C-STCK-STMR    -33.944904    150.764522                  4
4    C-STCK-STMR    -33.944361    150.764585                  5
..           ...           ...           ...                ...
311  C-STMR-STCK    -33.944361    150.764585                151
312  C-STMR-STCK    -33.944904    150.764522                152
313  C-STMR-STCK    -33.945699    150.764352                153
314  C-STMR-STCK    -33.948376    150.763887                154
315  C-STMR-STCK    -33.947502    150.756661                155

[316 rows x 4 columns]

In [20]:
# B road (Aerotropolis - Business Park)

twayB_aero_bprk = routeshapes.loc[routeshapes['shape_id']=='B-Tway-ToAirport'].sort_values('shape_pt_sequence')
twayB_aero_bprk = twayB_aero_bprk.reset_index(drop=True)
twayB_aero_bprk['shape_pt_sequence'] = twayB_aero_bprk.index+1
twayB_aero_bprk['shape_id'] = 'B-AERO-BPRK'

twayB_bprk_aero = routeshapes.loc[routeshapes['shape_id']=='B-Tway-FromAirport'].sort_values('shape_pt_sequence')
twayB_bprk_aero = twayB_bprk_aero.reset_index(drop=True)
twayB_bprk_aero['shape_pt_sequence'] = twayB_bprk_aero.index+1
twayB_bprk_aero['shape_id'] = 'B-BPRK-AERO'

twayB = twayB_aero_bprk.append(twayB_bprk_aero, ignore_index=True)
twayB

       shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0   B-AERO-BPRK    -33.920477    150.735168                  1
1   B-AERO-BPRK    -33.920374    150.734415                  2
2   B-AERO-BPRK    -33.920262    150.733601                  3
3   B-AERO-BPRK    -33.920169    150.732930                  4
4   B-AERO-BPRK    -33.920039    150.731982                  5
..          ...           ...           ...                ...
74  B-BPRK-AERO    -33.920039    150.731982                 36
75  B-BPRK-AERO    -33.920169    150.732930                 37
76  B-BPRK-AERO    -33.920262    150.733601                 38
77  B-BPRK-AERO    -33.920374    150.734415                 39
78  B-BPRK-AERO    -33.920477    150.735168                 40

[79 rows x 4 columns]

In [21]:
futureTways = tway15th.append(tway10th).append(tway20th).append(tway25th).append(twayE).append(twayD).append(twayC).append(twayB).reset_index(drop=True)
futureTways['shape_id'].unique()

array(['15th-LVPL-AERO', '15th-AERO-LVPL', '10th-CSLA-ASTH',
       '10th-ASTH-CSLA', '20th-LVPL-AERO', '20th-AERO-LVPL',
       '25th-CBMT-BPRK', '25th-BPRK-CBMT', 'E-LPTN-BPRK', 'E-BPRK-LPTN',
       'D-RSMR-MTDT', 'D-MTDT-RSMR', 'C-STCK-STMR', 'C-STMR-STCK',
       'B-AERO-BPRK', 'B-BPRK-AERO'], dtype=object)

In [22]:
#futureTways.to_csv('./Shapes/Future_Tways.csv', index=False)

### Local routes

In [23]:
routeshapes['shape_id'].unique()

array(['FAST_Aerotropolis', 'Aerotropolis_FAST', 'E-Tway-FromLeppington',
       'E-Tway-ToLeppington', 'B-Tway-ToAirport', 'B-Tway-FromAirport',
       '10thAv-Aerotropolis-Casula', '10thAv-Casula-Aerotropolis',
       '20thAv-BadgerysCreek-Austral', '20thAv-Austral-BadgerysCreek',
       '25thAv-BusinessPark-ElizabethDrive',
       '25thAv-ElizabethDrive-BusinessPark', '20thAv-FAST-Austral',
       '20thAv-Austral-FAST', '25thAv-ElizabethDrive-Cabramatta',
       '25thAv-Cabramatta-ElizabethDrive',
       '20thAv-BadgerysCreek-Aerotropolis',
       '20thAv-Aerotropolis-BadgerysCreek',
       'E-Tway-BadgerysCreek-BusinessPark',
       'E-Tway-BusinessPark-BadgerysCreek', 'Connection-ToCasula',
       'Connection-FromCasula', 'Connection-ToMtDruitt',
       'Connection-FromMtDruitt', 'Connection-ToStMarys',
       'Connection-FromStMarys', 'D-Tway-Rossmore-ElizabethDrive',
       'D-Tway-ElizabethDrive-Rossmore',
       'C-Tway-SouthCreek-ElizabethDrive',
       'C-Tway-ElizabethDrive-SouthCreek', '20thAv_BadgerysCreek_FAST',
       '20thAv_FAST_BadgerysCreek', 'To_Austral_SE_S',
       'From_Austral_SE_S', 'To_Austral_SE_E', 'From_Austral_SE_E',
       'To_Austral_SE_W', 'From_Austral_SE_W', 'To_Austral_SE_N',
       'From_Austral_SE_N', 'To_Austral_SW_E', 'From_Austral_SW_E',
       'To_Austral_SW_N', 'From_Austral_SW_N', 'To_Austral_SW_W',
       'From_Austral_SW_W', 'To_Austral_SW_S', 'From_Austral_SW_S',
       'To_Austral_NW_E', 'From_Austral_NW_E', 'To_Austral_NW_N',
       'From_Austral_NW_N', 'To_Austral_NW_S', 'From_Austral_NW_S',
       'To_Austral_NW_W', 'From_Austral_NW_W', 'To_Austral_NE_S',
       'From_Austral_NE_S', 'To_Rossmore_NW_S', 'From_Rossmore_NW_S',
       'To_Rossmore_NW_E', 'From_Rossmore_NW_E', 'To_Rossmore_NW_N',
       'From_Rossmore_NW_N', 'To_Rossmore_NW_W', 'From_Rossmore_NW_W',
       'To_Rossmore_SE_W', 'From_Rossmore_SE_W', 'To_Rossmore_SE_S',
       'From_Rossmore_SE_S', 'To_Rossmore_SE_E', 'From_Rossmore_SE_E',
       'To_Rossmore_SE_N', 'From_Rossmore_SE_N', 'To_Rossmore_SW_W',
       'From_Rossmore_SW_W', 'To_Rossmore_SW_S', 'From_Rossmore_SW_S',
       'To_Rossmore_SW_E', 'From_Rossmore_SW_E', 'To_Rossmore_SW_N',
       'From_Rossmore_SW_N', 'To_KempsCreek_NW_W', 'From_KempsCreek_NW_W',
       'To_KempsCreek_NW_S', 'From_KempsCreek_NW_S', 'To_KempsCreek_NW_N',
       'From_KempsCreek_NW_N', 'To_KempsCreek_SE_W',
       'From_KempsCreek_SE_W', 'To_KempsCreek_SE_S',
       'From_KempsCreek_SE_S', 'To_KempsCreek_SE_E',
       'From_KempsCreek_SE_E', 'To_KempsCreek_SE_N',
       'From_KempsCreek_SE_N', 'To_KempsCreek_SW_W',
       'From_KempsCreek_SW_W', 'To_KempsCreek_SW_S',
       'From_KempsCreek_SW_S', 'To_KempsCreek_SW_E',
       'From_KempsCreek_SW_E', 'To_KempsCreek_SW_N',
       'From_KempsCreek_SW_N', 'From_Austral_NE_E', 'To_Austral_NE_E',
       'From_Austral_NE_N', 'To_Austral_NE_N', 'From_Austral_NE_W',
       'To_Austral_NE_W', 'From_KempsCreek_NE_N', 'To_KempsCreek_NE_N',
       'To_KempsCreek_NE_S', 'From_KempsCreek_NE_S', 'To_KempsCreek_NE_W',
       'From_KempsCreek_NE_W', 'To_KempsCreek_NW_E',
       'From_KempsCreek_NW_E', 'From_Rossmore_NE_E', 'To_Rossmore_NE_E',
       'To_Rossmore_NE_N', 'From_Rossmore_NE_N', 'From_Rossmore_NE_S',
       'To_Rossmore_NE_S', 'To_Rossmore_NE_W', 'From_Rossmore_NE_W',
       'To_KempsCreek_NE_E', 'From_KempsCreek_NE_E', 'TT-2056-austral',
       'TT_r-2056-austral', 'FAST_MG_TOD', 'MG_FAST_TOD'], dtype=object)

In [24]:
# Austral NE
 
austral_NE_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
austral_NE_E_to = austral_NE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_NE_E'].sort_values('shape_pt_sequence'))
austral_NE_E_to = austral_NE_E_to.reset_index(drop=True)
austral_NE_E_to['shape_pt_sequence'] = austral_NE_E_to.index+1
austral_NE_E_to['shape_id'] = 'Austral-NE-E-to'

austral_NE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NE_E'].sort_values('shape_pt_sequence')
austral_NE_E_from = austral_NE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
austral_NE_E_from = austral_NE_E_from.reset_index(drop=True)
austral_NE_E_from['shape_pt_sequence'] = austral_NE_E_from.index+1
austral_NE_E_from['shape_id'] = 'Austral-NE-E-from'

austral_NE_N_to = routeshapes.loc[routeshapes['shape_id']=='E-Tway-BusinessPark-BadgerysCreek'].sort_values('shape_pt_sequence')
austral_NE_N_to = austral_NE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-BadgerysCreek-Austral'].sort_values('shape_pt_sequence'))
austral_NE_N_to = austral_NE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_NE_N'].sort_values('shape_pt_sequence'))
austral_NE_N_to = austral_NE_N_to.reset_index(drop=True)
austral_NE_N_to['shape_pt_sequence'] = austral_NE_N_to.index+1
austral_NE_N_to['shape_id'] = 'Austral-NE-N-to'

austral_NE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NE_N'].sort_values('shape_pt_sequence')
austral_NE_N_from = austral_NE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-Austral-BadgerysCreek'].sort_values('shape_pt_sequence'))
austral_NE_N_from = austral_NE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='E-Tway-BadgerysCreek-BusinessPark'].sort_values('shape_pt_sequence'))
austral_NE_N_from = austral_NE_N_from.reset_index(drop=True)
austral_NE_N_from['shape_pt_sequence'] = austral_NE_N_from.index+1
austral_NE_N_from['shape_id'] = 'Austral-NE-N-from'

austral_NE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_NE_S'].sort_values('shape_pt_sequence')
austral_NE_S_to = austral_NE_S_to.reset_index(drop=True)
austral_NE_S_to['shape_pt_sequence'] = austral_NE_S_to.index+1
austral_NE_S_to['shape_id'] = 'Austral-NE-S-to'

austral_NE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NE_S'].sort_values('shape_pt_sequence')
austral_NE_S_from = austral_NE_S_from.reset_index(drop=True)
austral_NE_S_from['shape_pt_sequence'] = austral_NE_S_from.index+1
austral_NE_S_from['shape_id'] = 'Austral-NE-S-from'

austral_NE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_NE_W'].sort_values('shape_pt_sequence')
austral_NE_W_to = austral_NE_W_to.reset_index(drop=True)
austral_NE_W_to['shape_pt_sequence'] = austral_NE_W_to.index+1
austral_NE_W_to['shape_id'] = 'Austral-NE-W-to'

austral_NE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NE_W'].sort_values('shape_pt_sequence')
austral_NE_W_from = austral_NE_W_from.reset_index(drop=True)
austral_NE_W_from['shape_pt_sequence'] = austral_NE_W_from.index+1
austral_NE_W_from['shape_id'] = 'Austral-NE-W-from'

austral_NE = austral_NE_E_to.append(austral_NE_N_to).append(austral_NE_S_to).append(austral_NE_W_to).append(austral_NE_E_from).append(austral_NE_N_from).append(austral_NE_S_from).append(austral_NE_W_from)
austral_NE

             shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Austral-NE-E-to    -33.922966    150.926880                  1
1     Austral-NE-E-to    -33.922761    150.925374                  2
2     Austral-NE-E-to    -33.922714    150.925022                  3
3     Austral-NE-E-to    -33.922697    150.924901                  4
4     Austral-NE-E-to    -33.922544    150.923725                  5
..                ...           ...           ...                ...
47  Austral-NE-W-from    -33.911047    150.752946                 48
48  Austral-NE-W-from    -33.910092    150.746010                 49
49  Austral-NE-W-from    -33.915873    150.744865                 50
50  Austral-NE-W-from    -33.914919    150.737929                 51
51  Austral-NE-W-from    -33.920700    150.736783                 52

[864 rows x 4 columns]

In [25]:
# Austral SE
 
austral_SE_E_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromCasula'].sort_values('shape_pt_sequence')
austral_SE_E_to = austral_SE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_SE_E'].sort_values('shape_pt_sequence'))
austral_SE_E_to = austral_SE_E_to.reset_index(drop=True)
austral_SE_E_to['shape_pt_sequence'] = austral_SE_E_to.index+1
austral_SE_E_to['shape_id'] = 'Austral-SE-E-to'

austral_SE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SE_E'].sort_values('shape_pt_sequence')
austral_SE_E_from = austral_SE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToCasula'].sort_values('shape_pt_sequence'))
austral_SE_E_from = austral_SE_E_from.reset_index(drop=True)
austral_SE_E_from['shape_pt_sequence'] = austral_SE_E_from.index+1
austral_SE_E_from['shape_id'] = 'Austral-SE-E-from'

austral_SE_N_to = routeshapes.loc[routeshapes['shape_id']=='E-Tway-BusinessPark-BadgerysCreek'].sort_values('shape_pt_sequence')
austral_SE_N_to = austral_SE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-BadgerysCreek-Austral'].sort_values('shape_pt_sequence'))
austral_SE_N_to = austral_SE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_SE_N'].sort_values('shape_pt_sequence'))
austral_SE_N_to = austral_SE_N_to.reset_index(drop=True)
austral_SE_N_to['shape_pt_sequence'] = austral_SE_N_to.index+1
austral_SE_N_to['shape_id'] = 'Austral-SE-N-to'

austral_SE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SE_N'].sort_values('shape_pt_sequence')
austral_SE_N_from = austral_SE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='20thAv-Austral-BadgerysCreek'].sort_values('shape_pt_sequence'))
austral_SE_N_from = austral_SE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='E-Tway-BadgerysCreek-BusinessPark'].sort_values('shape_pt_sequence'))
austral_SE_N_from = austral_SE_N_from.reset_index(drop=True)
austral_SE_N_from['shape_pt_sequence'] = austral_SE_N_from.index+1
austral_SE_N_from['shape_id'] = 'Austral-SE-N-from'

austral_SE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_SE_S'].sort_values('shape_pt_sequence')
austral_SE_S_to = austral_SE_S_to.reset_index(drop=True)
austral_SE_S_to['shape_pt_sequence'] = austral_SE_S_to.index+1
austral_SE_S_to['shape_id'] = 'Austral-SE-S-to'

austral_SE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SE_S'].sort_values('shape_pt_sequence')
austral_SE_S_from = austral_SE_S_from.reset_index(drop=True)
austral_SE_S_from['shape_pt_sequence'] = austral_SE_S_from.index+1
austral_SE_S_from['shape_id'] = 'Austral-SE-S-from'

austral_SE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_SE_W'].sort_values('shape_pt_sequence')
austral_SE_W_to = austral_SE_W_to.reset_index(drop=True)
austral_SE_W_to['shape_pt_sequence'] = austral_SE_W_to.index+1
austral_SE_W_to['shape_id'] = 'Austral-SE-W-to'

austral_SE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SE_W'].sort_values('shape_pt_sequence')
austral_SE_W_from = austral_SE_W_from.reset_index(drop=True)
austral_SE_W_from['shape_pt_sequence'] = austral_SE_W_from.index+1
austral_SE_W_from['shape_id'] = 'Austral-SE-W-from'

austral_SE = austral_SE_E_to.append(austral_SE_N_to).append(austral_SE_S_to).append(austral_SE_W_to).append(austral_SE_E_from).append(austral_SE_N_from).append(austral_SE_S_from).append(austral_SE_W_from)
austral_SE

             shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Austral-SE-E-to    -33.949904    150.911435                  1
1     Austral-SE-E-to    -33.950275    150.911325                  2
2     Austral-SE-E-to    -33.950353    150.911280                  3
3     Austral-SE-E-to    -33.950489    150.911095                  4
4     Austral-SE-E-to    -33.950565    150.911058                  5
..                ...           ...           ...                ...
66  Austral-SE-W-from    -33.927604    150.750289                 67
67  Austral-SE-W-from    -33.928390    150.749508                 68
68  Austral-SE-W-from    -33.927435    150.742574                 69
69  Austral-SE-W-from    -33.934563    150.741161                 70
70  Austral-SE-W-from    -33.934464    150.740443                 71

[1239 rows x 4 columns]

In [26]:
# Austral NW
 
austral_NW_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
austral_NW_E_to = austral_NW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_NW_E'].sort_values('shape_pt_sequence'))
austral_NW_E_to = austral_NW_E_to.reset_index(drop=True)
austral_NW_E_to['shape_pt_sequence'] = austral_NW_E_to.index+1
austral_NW_E_to['shape_id'] = 'Austral-NW-E-to'

austral_NW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NW_E'].sort_values('shape_pt_sequence')
austral_NW_E_from = austral_NW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
austral_NW_E_from = austral_NW_E_from.reset_index(drop=True)
austral_NW_E_from['shape_pt_sequence'] = austral_NW_E_from.index+1
austral_NW_E_from['shape_id'] = 'Austral-NW-E-from'

austral_NW_N_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_NW_N'].sort_values('shape_pt_sequence')
austral_NW_N_to = austral_NW_N_to.reset_index(drop=True)
austral_NW_N_to['shape_pt_sequence'] = austral_NW_N_to.index+1
austral_NW_N_to['shape_id'] = 'Austral-NW-N-to'

austral_NW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NW_N'].sort_values('shape_pt_sequence')
austral_NW_N_from = austral_NW_N_from.reset_index(drop=True)
austral_NW_N_from['shape_pt_sequence'] = austral_NW_N_from.index+1
austral_NW_N_from['shape_id'] = 'Austral-NW-N-from'

austral_NW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_NW_S'].sort_values('shape_pt_sequence')
austral_NW_S_to = austral_NW_S_to.reset_index(drop=True)
austral_NW_S_to['shape_pt_sequence'] = austral_NW_S_to.index+1
austral_NW_S_to['shape_id'] = 'Austral-NW-S-to'

austral_NW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NW_S'].sort_values('shape_pt_sequence')
austral_NW_S_from = austral_NW_S_from.reset_index(drop=True)
austral_NW_S_from['shape_pt_sequence'] = austral_NW_S_from.index+1
austral_NW_S_from['shape_id'] = 'Austral-NW-S-from'

austral_NW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_NW_W'].sort_values('shape_pt_sequence')
austral_NW_W_to = austral_NW_W_to.reset_index(drop=True)
austral_NW_W_to['shape_pt_sequence'] = austral_NW_W_to.index+1
austral_NW_W_to['shape_id'] = 'Austral-NW-W-to'

austral_NW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_NW_W'].sort_values('shape_pt_sequence')
austral_NW_W_from = austral_NW_W_from.reset_index(drop=True)
austral_NW_W_from['shape_pt_sequence'] = austral_NW_W_from.index+1
austral_NW_W_from['shape_id'] = 'Austral-NW-W-from'

austral_NW = austral_NW_E_to.append(austral_NW_N_to).append(austral_NW_S_to).append(austral_NW_W_to).append(austral_NW_E_from).append(austral_NW_N_from).append(austral_NW_S_from).append(austral_NW_W_from)
austral_NW

             shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Austral-NW-E-to    -33.922966    150.926880                  1
1     Austral-NW-E-to    -33.922761    150.925374                  2
2     Austral-NW-E-to    -33.922714    150.925022                  3
3     Austral-NW-E-to    -33.922697    150.924901                  4
4     Austral-NW-E-to    -33.922544    150.923725                  5
..                ...           ...           ...                ...
56  Austral-NW-W-from    -33.911047    150.752946                 57
57  Austral-NW-W-from    -33.910092    150.746010                 58
58  Austral-NW-W-from    -33.915873    150.744865                 59
59  Austral-NW-W-from    -33.914919    150.737929                 60
60  Austral-NW-W-from    -33.920700    150.736783                 61

[988 rows x 4 columns]

In [27]:
# Austral SW
 
austral_SW_E_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromCasula'].sort_values('shape_pt_sequence')
austral_SW_E_to = austral_SW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Austral_SW_E'].sort_values('shape_pt_sequence'))
austral_SW_E_to = austral_SW_E_to.reset_index(drop=True)
austral_SW_E_to['shape_pt_sequence'] = austral_SW_E_to.index+1
austral_SW_E_to['shape_id'] = 'Austral-SW-E-to'

austral_SW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SW_E'].sort_values('shape_pt_sequence')
austral_SW_E_from = austral_SW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToCasula'].sort_values('shape_pt_sequence'))
austral_SW_E_from = austral_SW_E_from.reset_index(drop=True)
austral_SW_E_from['shape_pt_sequence'] = austral_SW_E_from.index+1
austral_SW_E_from['shape_id'] = 'Austral-SW-E-from'

austral_SW_N_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_SW_N'].sort_values('shape_pt_sequence')
austral_SW_N_to = austral_SW_N_to.reset_index(drop=True)
austral_SW_N_to['shape_pt_sequence'] = austral_SW_N_to.index+1
austral_SW_N_to['shape_id'] = 'Austral-SW-N-to'

austral_SW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SW_N'].sort_values('shape_pt_sequence')
austral_SW_N_from = austral_SW_N_from.reset_index(drop=True)
austral_SW_N_from['shape_pt_sequence'] = austral_SW_N_from.index+1
austral_SW_N_from['shape_id'] = 'Austral-SW-N-from'

austral_SW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_SW_S'].sort_values('shape_pt_sequence')
austral_SW_S_to = austral_SW_S_to.reset_index(drop=True)
austral_SW_S_to['shape_pt_sequence'] = austral_SW_S_to.index+1
austral_SW_S_to['shape_id'] = 'Austral-SW-S-to'

austral_SW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SW_S'].sort_values('shape_pt_sequence')
austral_SW_S_from = austral_SW_S_from.reset_index(drop=True)
austral_SW_S_from['shape_pt_sequence'] = austral_SW_S_from.index+1
austral_SW_S_from['shape_id'] = 'Austral-SW-S-from'

austral_SW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Austral_SW_W'].sort_values('shape_pt_sequence')
austral_SW_W_to = austral_SW_W_to.reset_index(drop=True)
austral_SW_W_to['shape_pt_sequence'] = austral_SW_W_to.index+1
austral_SW_W_to['shape_id'] = 'Austral-SW-W-to'

austral_SW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Austral_SW_W'].sort_values('shape_pt_sequence')
austral_SW_W_from = austral_SW_W_from.reset_index(drop=True)
austral_SW_W_from['shape_pt_sequence'] = austral_SW_W_from.index+1
austral_SW_W_from['shape_id'] = 'Austral-SW-W-from'

austral_SW = austral_SW_E_to.append(austral_SW_N_to).append(austral_SW_S_to).append(austral_SW_W_to).append(austral_SW_E_from).append(austral_SW_N_from).append(austral_SW_S_from).append(austral_SW_W_from)
austral_SW

             shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Austral-SW-E-to    -33.949904    150.911435                  1
1     Austral-SW-E-to    -33.950275    150.911325                  2
2     Austral-SW-E-to    -33.950353    150.911280                  3
3     Austral-SW-E-to    -33.950489    150.911095                  4
4     Austral-SW-E-to    -33.950565    150.911058                  5
..                ...           ...           ...                ...
37  Austral-SW-W-from    -33.927604    150.750289                 38
38  Austral-SW-W-from    -33.928390    150.749508                 39
39  Austral-SW-W-from    -33.927435    150.742574                 40
40  Austral-SW-W-from    -33.934563    150.741161                 41
41  Austral-SW-W-from    -33.934464    150.740443                 42

[1122 rows x 4 columns]

In [28]:
# Rossmore SE
 
rossmore_SE_E_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromCasula'].sort_values('shape_pt_sequence')
rossmore_SE_E_to = rossmore_SE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SE_E'].sort_values('shape_pt_sequence'))
rossmore_SE_E_to = rossmore_SE_E_to.reset_index(drop=True)
rossmore_SE_E_to['shape_pt_sequence'] = rossmore_SE_E_to.index+1
rossmore_SE_E_to['shape_id'] = 'Rossmore-SE-E-to'

rossmore_SE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SE_E'].sort_values('shape_pt_sequence')
rossmore_SE_E_from = rossmore_SE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToCasula'].sort_values('shape_pt_sequence'))
rossmore_SE_E_from = rossmore_SE_E_from.reset_index(drop=True)
rossmore_SE_E_from['shape_pt_sequence'] = rossmore_SE_E_from.index+1
rossmore_SE_E_from['shape_id'] = 'Rossmore-SE-E-from'

rossmore_SE_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromMtDruitt'].sort_values('shape_pt_sequence')
rossmore_SE_N_to = rossmore_SE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SE_N'].sort_values('shape_pt_sequence'))
rossmore_SE_N_to = rossmore_SE_N_to.reset_index(drop=True)
rossmore_SE_N_to['shape_pt_sequence'] = rossmore_SE_N_to.index+1
rossmore_SE_N_to['shape_id'] = 'Rossmore-SE-N-to'

rossmore_SE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SE_N'].sort_values('shape_pt_sequence')
rossmore_SE_N_from = rossmore_SE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToMtDruitt'].sort_values('shape_pt_sequence'))
rossmore_SE_N_from = rossmore_SE_N_from.reset_index(drop=True)
rossmore_SE_N_from['shape_pt_sequence'] = rossmore_SE_N_from.index+1
rossmore_SE_N_from['shape_id'] = 'Rossmore-SE-N-from'

rossmore_SE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SE_S'].sort_values('shape_pt_sequence')
rossmore_SE_S_to = rossmore_SE_S_to.reset_index(drop=True)
rossmore_SE_S_to['shape_pt_sequence'] = rossmore_SE_S_to.index+1
rossmore_SE_S_to['shape_id'] = 'Rossmore-SE-S-to'

rossmore_SE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SE_S'].sort_values('shape_pt_sequence')
rossmore_SE_S_from = rossmore_SE_S_from.reset_index(drop=True)
rossmore_SE_S_from['shape_pt_sequence'] = rossmore_SE_S_from.index+1
rossmore_SE_S_from['shape_id'] = 'Rossmore-SE-S-from'

rossmore_SE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SE_W'].sort_values('shape_pt_sequence')
rossmore_SE_W_to = rossmore_SE_W_to.reset_index(drop=True)
rossmore_SE_W_to['shape_pt_sequence'] = rossmore_SE_W_to.index+1
rossmore_SE_W_to['shape_id'] = 'Rossmore-SE-W-to'

rossmore_SE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SE_W'].sort_values('shape_pt_sequence')
rossmore_SE_W_from = rossmore_SE_W_from.reset_index(drop=True)
rossmore_SE_W_from['shape_pt_sequence'] = rossmore_SE_W_from.index+1
rossmore_SE_W_from['shape_id'] = 'Rossmore-SE-W-from'

rossmore_SE = rossmore_SE_E_to.append(rossmore_SE_N_to).append(rossmore_SE_S_to).append(rossmore_SE_W_to).append(rossmore_SE_E_from).append(rossmore_SE_N_from).append(rossmore_SE_S_from).append(rossmore_SE_W_from)
rossmore_SE

              shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Rossmore-SE-E-to    -33.949904    150.911435                  1
1     Rossmore-SE-E-to    -33.950275    150.911325                  2
2     Rossmore-SE-E-to    -33.950353    150.911280                  3
3     Rossmore-SE-E-to    -33.950489    150.911095                  4
4     Rossmore-SE-E-to    -33.950565    150.911058                  5
..                 ...           ...           ...                ...
14  Rossmore-SE-W-from    -33.927604    150.750289                 15
15  Rossmore-SE-W-from    -33.928390    150.749508                 16
16  Rossmore-SE-W-from    -33.927435    150.742574                 17
17  Rossmore-SE-W-from    -33.934563    150.741161                 18
18  Rossmore-SE-W-from    -33.934464    150.740443                 19

[1381 rows x 4 columns]

In [29]:
# Rossmore SW
 
rossmore_SW_E_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromCasula'].sort_values('shape_pt_sequence')
rossmore_SW_E_to = rossmore_SW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SW_E'].sort_values('shape_pt_sequence'))
rossmore_SW_E_to = rossmore_SW_E_to.reset_index(drop=True)
rossmore_SW_E_to['shape_pt_sequence'] = rossmore_SW_E_to.index+1
rossmore_SW_E_to['shape_id'] = 'Rossmore-SW-E-to'

rossmore_SW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SW_E'].sort_values('shape_pt_sequence')
rossmore_SW_E_from = rossmore_SW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToCasula'].sort_values('shape_pt_sequence'))
rossmore_SW_E_from = rossmore_SW_E_from.reset_index(drop=True)
rossmore_SW_E_from['shape_pt_sequence'] = rossmore_SW_E_from.index+1
rossmore_SW_E_from['shape_id'] = 'Rossmore-SW-E-from'

rossmore_SW_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromStMarys'].sort_values('shape_pt_sequence')
rossmore_SW_N_to = rossmore_SW_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SW_N'].sort_values('shape_pt_sequence'))
rossmore_SW_N_to = rossmore_SW_N_to.reset_index(drop=True)
rossmore_SW_N_to['shape_pt_sequence'] = rossmore_SW_N_to.index+1
rossmore_SW_N_to['shape_id'] = 'Rossmore-SW-N-to'

rossmore_SW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SW_N'].sort_values('shape_pt_sequence')
rossmore_SW_N_from = rossmore_SW_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToStMarys'].sort_values('shape_pt_sequence'))
rossmore_SW_N_from = rossmore_SW_N_from.reset_index(drop=True)
rossmore_SW_N_from['shape_pt_sequence'] = rossmore_SW_N_from.index+1
rossmore_SW_N_from['shape_id'] = 'Rossmore-SW-N-from'

rossmore_SW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SW_S'].sort_values('shape_pt_sequence')
rossmore_SW_S_to = rossmore_SW_S_to.reset_index(drop=True)
rossmore_SW_S_to['shape_pt_sequence'] = rossmore_SW_S_to.index+1
rossmore_SW_S_to['shape_id'] = 'Rossmore-SW-S-to'

rossmore_SW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SW_S'].sort_values('shape_pt_sequence')
rossmore_SW_S_from = rossmore_SW_S_from.reset_index(drop=True)
rossmore_SW_S_from['shape_pt_sequence'] = rossmore_SW_S_from.index+1
rossmore_SW_S_from['shape_id'] = 'Rossmore-SW-S-from'

rossmore_SW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_SW_W'].sort_values('shape_pt_sequence')
rossmore_SW_W_to = rossmore_SW_W_to.reset_index(drop=True)
rossmore_SW_W_to['shape_pt_sequence'] = rossmore_SW_W_to.index+1
rossmore_SW_W_to['shape_id'] = 'Rossmore-SW-W-to'

rossmore_SW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_SW_W'].sort_values('shape_pt_sequence')
rossmore_SW_W_from = rossmore_SW_W_from.reset_index(drop=True)
rossmore_SW_W_from['shape_pt_sequence'] = rossmore_SW_W_from.index+1
rossmore_SW_W_from['shape_id'] = 'Rossmore-SW-W-from'

rossmore_SW = rossmore_SW_E_to.append(rossmore_SW_N_to).append(rossmore_SW_S_to).append(rossmore_SW_W_to).append(rossmore_SW_E_from).append(rossmore_SW_N_from).append(rossmore_SW_S_from).append(rossmore_SW_W_from)
rossmore_SW

              shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Rossmore-SW-E-to    -33.949904    150.911435                  1
1     Rossmore-SW-E-to    -33.950275    150.911325                  2
2     Rossmore-SW-E-to    -33.950353    150.911280                  3
3     Rossmore-SW-E-to    -33.950489    150.911095                  4
4     Rossmore-SW-E-to    -33.950565    150.911058                  5
..                 ...           ...           ...                ...
11  Rossmore-SW-W-from    -33.927604    150.750289                 12
12  Rossmore-SW-W-from    -33.928390    150.749508                 13
13  Rossmore-SW-W-from    -33.927435    150.742574                 14
14  Rossmore-SW-W-from    -33.934563    150.741161                 15
15  Rossmore-SW-W-from    -33.934464    150.740443                 16

[1158 rows x 4 columns]

In [30]:
# Rossmore NE
 
rossmore_NE_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
rossmore_NE_E_to = rossmore_NE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NE_E'].sort_values('shape_pt_sequence'))
rossmore_NE_E_to = rossmore_NE_E_to.reset_index(drop=True)
rossmore_NE_E_to['shape_pt_sequence'] = rossmore_NE_E_to.index+1
rossmore_NE_E_to['shape_id'] = 'Rossmore-NE-E-to'

rossmore_NE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NE_E'].sort_values('shape_pt_sequence')
rossmore_NE_E_from = rossmore_NE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
rossmore_NE_E_from = rossmore_NE_E_from.reset_index(drop=True)
rossmore_NE_E_from['shape_pt_sequence'] = rossmore_NE_E_from.index+1
rossmore_NE_E_from['shape_id'] = 'Rossmore-NE-E-from'

rossmore_NE_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromMtDruitt'].sort_values('shape_pt_sequence')
rossmore_NE_N_to = rossmore_NE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NE_N'].sort_values('shape_pt_sequence'))
rossmore_NE_N_to = rossmore_NE_N_to.reset_index(drop=True)
rossmore_NE_N_to['shape_pt_sequence'] = rossmore_NE_N_to.index+1
rossmore_NE_N_to['shape_id'] = 'Rossmore-NE-N-to'

rossmore_NE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NE_N'].sort_values('shape_pt_sequence')
rossmore_NE_N_from = rossmore_NE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToMtDruitt'].sort_values('shape_pt_sequence'))
rossmore_NE_N_from = rossmore_NE_N_from.reset_index(drop=True)
rossmore_NE_N_from['shape_pt_sequence'] = rossmore_NE_N_from.index+1
rossmore_NE_N_from['shape_id'] = 'Rossmore-NE-N-from'

rossmore_NE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NE_S'].sort_values('shape_pt_sequence')
rossmore_NE_S_to = rossmore_NE_S_to.reset_index(drop=True)
rossmore_NE_S_to['shape_pt_sequence'] = rossmore_NE_S_to.index+1
rossmore_NE_S_to['shape_id'] = 'Rossmore-NE-S-to'

rossmore_NE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NE_S'].sort_values('shape_pt_sequence')
rossmore_NE_S_from = rossmore_NE_S_from.reset_index(drop=True)
rossmore_NE_S_from['shape_pt_sequence'] = rossmore_NE_S_from.index+1
rossmore_NE_S_from['shape_id'] = 'Rossmore-NE-S-from'

rossmore_NE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NE_W'].sort_values('shape_pt_sequence')
rossmore_NE_W_to = rossmore_NE_W_to.reset_index(drop=True)
rossmore_NE_W_to['shape_pt_sequence'] = rossmore_NE_W_to.index+1
rossmore_NE_W_to['shape_id'] = 'Rossmore-NE-W-to'

rossmore_NE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NE_W'].sort_values('shape_pt_sequence')
rossmore_NE_W_from = rossmore_NE_W_from.reset_index(drop=True)
rossmore_NE_W_from['shape_pt_sequence'] = rossmore_NE_W_from.index+1
rossmore_NE_W_from['shape_id'] = 'Rossmore-NE-W-from'

rossmore_NE = rossmore_NE_E_to.append(rossmore_NE_N_to).append(rossmore_NE_S_to).append(rossmore_NE_W_to).append(rossmore_NE_E_from).append(rossmore_NE_N_from).append(rossmore_NE_S_from).append(rossmore_NE_W_from)
rossmore_NE

              shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Rossmore-NE-E-to    -33.922966    150.926880                  1
1     Rossmore-NE-E-to    -33.922761    150.925374                  2
2     Rossmore-NE-E-to    -33.922714    150.925022                  3
3     Rossmore-NE-E-to    -33.922697    150.924901                  4
4     Rossmore-NE-E-to    -33.922544    150.923725                  5
..                 ...           ...           ...                ...
17  Rossmore-NE-W-from    -33.911047    150.752946                 18
18  Rossmore-NE-W-from    -33.910092    150.746010                 19
19  Rossmore-NE-W-from    -33.915873    150.744865                 20
20  Rossmore-NE-W-from    -33.914919    150.737929                 21
21  Rossmore-NE-W-from    -33.920700    150.736783                 22

[1072 rows x 4 columns]

In [31]:
# Rossmore NW
 
rossmore_NW_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
rossmore_NW_E_to = rossmore_NW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NW_E'].sort_values('shape_pt_sequence'))
rossmore_NW_E_to = rossmore_NW_E_to.reset_index(drop=True)
rossmore_NW_E_to['shape_pt_sequence'] = rossmore_NW_E_to.index+1
rossmore_NW_E_to['shape_id'] = 'Rossmore-NW-E-to'

rossmore_NW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NW_E'].sort_values('shape_pt_sequence')
rossmore_NW_E_from = rossmore_NW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
rossmore_NW_E_from = rossmore_NW_E_from.reset_index(drop=True)
rossmore_NW_E_from['shape_pt_sequence'] = rossmore_NW_E_from.index+1
rossmore_NW_E_from['shape_id'] = 'Rossmore-NW-E-from'

rossmore_NW_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromStMarys'].sort_values('shape_pt_sequence')
rossmore_NW_N_to = rossmore_NW_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NW_N'].sort_values('shape_pt_sequence'))
rossmore_NW_N_to = rossmore_NW_N_to.reset_index(drop=True)
rossmore_NW_N_to['shape_pt_sequence'] = rossmore_NW_N_to.index+1
rossmore_NW_N_to['shape_id'] = 'Rossmore-NW-N-to'

rossmore_NW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NW_N'].sort_values('shape_pt_sequence')
rossmore_NW_N_from = rossmore_NW_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToStMarys'].sort_values('shape_pt_sequence'))
rossmore_NW_N_from = rossmore_NW_N_from.reset_index(drop=True)
rossmore_NW_N_from['shape_pt_sequence'] = rossmore_NW_N_from.index+1
rossmore_NW_N_from['shape_id'] = 'Rossmore-NW-N-from'

rossmore_NW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NW_S'].sort_values('shape_pt_sequence')
rossmore_NW_S_to = rossmore_NW_S_to.reset_index(drop=True)
rossmore_NW_S_to['shape_pt_sequence'] = rossmore_NW_S_to.index+1
rossmore_NW_S_to['shape_id'] = 'Rossmore-NW-S-to'

rossmore_NW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NW_S'].sort_values('shape_pt_sequence')
rossmore_NW_S_from = rossmore_NW_S_from.reset_index(drop=True)
rossmore_NW_S_from['shape_pt_sequence'] = rossmore_NW_S_from.index+1
rossmore_NW_S_from['shape_id'] = 'Rossmore-NW-S-from'

rossmore_NW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_Rossmore_NW_W'].sort_values('shape_pt_sequence')
rossmore_NW_W_to = rossmore_NW_W_to.reset_index(drop=True)
rossmore_NW_W_to['shape_pt_sequence'] = rossmore_NW_W_to.index+1
rossmore_NW_W_to['shape_id'] = 'Rossmore-NW-W-to'

rossmore_NW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_Rossmore_NW_W'].sort_values('shape_pt_sequence')
rossmore_NW_W_from = rossmore_NW_W_from.reset_index(drop=True)
rossmore_NW_W_from['shape_pt_sequence'] = rossmore_NW_W_from.index+1
rossmore_NW_W_from['shape_id'] = 'Rossmore-NW-W-from'

rossmore_NW = rossmore_NW_E_to.append(rossmore_NW_N_to).append(rossmore_NW_S_to).append(rossmore_NW_W_to).append(rossmore_NW_E_from).append(rossmore_NW_N_from).append(rossmore_NW_S_from).append(rossmore_NW_W_from)
rossmore_NW

              shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     Rossmore-NW-E-to    -33.922966    150.926880                  1
1     Rossmore-NW-E-to    -33.922761    150.925374                  2
2     Rossmore-NW-E-to    -33.922714    150.925022                  3
3     Rossmore-NW-E-to    -33.922697    150.924901                  4
4     Rossmore-NW-E-to    -33.922544    150.923725                  5
..                 ...           ...           ...                ...
8   Rossmore-NW-W-from    -33.911047    150.752946                  9
9   Rossmore-NW-W-from    -33.910092    150.746010                 10
10  Rossmore-NW-W-from    -33.915873    150.744865                 11
11  Rossmore-NW-W-from    -33.914919    150.737929                 12
12  Rossmore-NW-W-from    -33.920700    150.736783                 13

[911 rows x 4 columns]

In [32]:
# KempsCreek SE
 
kempscreek_SE_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
kempscreek_SE_E_to = kempscreek_SE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SE_E'].sort_values('shape_pt_sequence'))
kempscreek_SE_E_to = kempscreek_SE_E_to.reset_index(drop=True)
kempscreek_SE_E_to['shape_pt_sequence'] = kempscreek_SE_E_to.index+1
kempscreek_SE_E_to['shape_id'] = 'KempsCreek-SE-E-to'

kempscreek_SE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SE_E'].sort_values('shape_pt_sequence')
kempscreek_SE_E_from = kempscreek_SE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
kempscreek_SE_E_from = kempscreek_SE_E_from.reset_index(drop=True)
kempscreek_SE_E_from['shape_pt_sequence'] = kempscreek_SE_E_from.index+1
kempscreek_SE_E_from['shape_id'] = 'KempsCreek-SE-E-from'

kempscreek_SE_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromMtDruitt'].sort_values('shape_pt_sequence')
kempscreek_SE_N_to = kempscreek_SE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SE_N'].sort_values('shape_pt_sequence'))
kempscreek_SE_N_to = kempscreek_SE_N_to.reset_index(drop=True)
kempscreek_SE_N_to['shape_pt_sequence'] = kempscreek_SE_N_to.index+1
kempscreek_SE_N_to['shape_id'] = 'KempsCreek-SE-N-to'

kempscreek_SE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SE_N'].sort_values('shape_pt_sequence')
kempscreek_SE_N_from = kempscreek_SE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToMtDruitt'].sort_values('shape_pt_sequence'))
kempscreek_SE_N_from = kempscreek_SE_N_from.reset_index(drop=True)
kempscreek_SE_N_from['shape_pt_sequence'] = kempscreek_SE_N_from.index+1
kempscreek_SE_N_from['shape_id'] = 'KempsCreek-SE-N-from'

kempscreek_SE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SE_S'].sort_values('shape_pt_sequence')
kempscreek_SE_S_to = kempscreek_SE_S_to.reset_index(drop=True)
kempscreek_SE_S_to['shape_pt_sequence'] = kempscreek_SE_S_to.index+1
kempscreek_SE_S_to['shape_id'] = 'KempsCreek-SE-S-to'

kempscreek_SE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SE_S'].sort_values('shape_pt_sequence')
kempscreek_SE_S_from = kempscreek_SE_S_from.reset_index(drop=True)
kempscreek_SE_S_from['shape_pt_sequence'] = kempscreek_SE_S_from.index+1
kempscreek_SE_S_from['shape_id'] = 'KempsCreek-SE-S-from'

kempscreek_SE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SE_W'].sort_values('shape_pt_sequence')
kempscreek_SE_W_to = kempscreek_SE_W_to.reset_index(drop=True)
kempscreek_SE_W_to['shape_pt_sequence'] = kempscreek_SE_W_to.index+1
kempscreek_SE_W_to['shape_id'] = 'KempsCreek-SE-W-to'

kempscreek_SE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SE_W'].sort_values('shape_pt_sequence')
kempscreek_SE_W_from = kempscreek_SE_W_from.reset_index(drop=True)
kempscreek_SE_W_from['shape_pt_sequence'] = kempscreek_SE_W_from.index+1
kempscreek_SE_W_from['shape_id'] = 'KempsCreek-SE-W-from'

kempscreek_SE = kempscreek_SE_E_to.append(kempscreek_SE_N_to).append(kempscreek_SE_S_to).append(kempscreek_SE_W_to).append(kempscreek_SE_E_from).append(kempscreek_SE_N_from).append(kempscreek_SE_S_from).append(kempscreek_SE_W_from)
kempscreek_SE

                shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     KempsCreek-SE-E-to    -33.922966    150.926880                  1
1     KempsCreek-SE-E-to    -33.922761    150.925374                  2
2     KempsCreek-SE-E-to    -33.922714    150.925022                  3
3     KempsCreek-SE-E-to    -33.922697    150.924901                  4
4     KempsCreek-SE-E-to    -33.922544    150.923725                  5
..                   ...           ...           ...                ...
21  KempsCreek-SE-W-from    -33.904311    150.747155                 22
22  KempsCreek-SE-W-from    -33.910092    150.746010                 23
23  KempsCreek-SE-W-from    -33.915873    150.744865                 24
24  KempsCreek-SE-W-from    -33.914919    150.737929                 25
25  KempsCreek-SE-W-from    -33.920700    150.736783                 26

[1129 rows x 4 columns]

In [33]:
# KempsCreek NE
 
kempscreek_NE_E_to = routeshapes.loc[routeshapes['shape_id']=='25thAv-Cabramatta-ElizabethDrive'].sort_values('shape_pt_sequence')
kempscreek_NE_E_to = kempscreek_NE_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NE_E'].sort_values('shape_pt_sequence'))
kempscreek_NE_E_to = kempscreek_NE_E_to.reset_index(drop=True)
kempscreek_NE_E_to['shape_pt_sequence'] = kempscreek_NE_E_to.index+1
kempscreek_NE_E_to['shape_id'] = 'KempsCreek-NE-E-to'

kempscreek_NE_E_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NE_E'].sort_values('shape_pt_sequence')
kempscreek_NE_E_from = kempscreek_NE_E_from.append(routeshapes.loc[routeshapes['shape_id']=='25thAv-ElizabethDrive-Cabramatta'].sort_values('shape_pt_sequence'))
kempscreek_NE_E_from = kempscreek_NE_E_from.reset_index(drop=True)
kempscreek_NE_E_from['shape_pt_sequence'] = kempscreek_NE_E_from.index+1
kempscreek_NE_E_from['shape_id'] = 'KempsCreek-NE-E-from'

kempscreek_NE_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromMtDruitt'].sort_values('shape_pt_sequence')
kempscreek_NE_N_to = kempscreek_NE_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NE_N'].sort_values('shape_pt_sequence'))
kempscreek_NE_N_to = kempscreek_NE_N_to.reset_index(drop=True)
kempscreek_NE_N_to['shape_pt_sequence'] = kempscreek_NE_N_to.index+1
kempscreek_NE_N_to['shape_id'] = 'KempsCreek-NE-N-to'

kempscreek_NE_N_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NE_N'].sort_values('shape_pt_sequence')
kempscreek_NE_N_from = kempscreek_NE_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToMtDruitt'].sort_values('shape_pt_sequence'))
kempscreek_NE_N_from = kempscreek_NE_N_from.reset_index(drop=True)
kempscreek_NE_N_from['shape_pt_sequence'] = kempscreek_NE_N_from.index+1
kempscreek_NE_N_from['shape_id'] = 'KempsCreek-NE-N-from'

kempscreek_NE_S_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NE_S'].sort_values('shape_pt_sequence')
kempscreek_NE_S_to = kempscreek_NE_S_to.reset_index(drop=True)
kempscreek_NE_S_to['shape_pt_sequence'] = kempscreek_NE_S_to.index+1
kempscreek_NE_S_to['shape_id'] = 'KempsCreek-NE-S-to'

kempscreek_NE_S_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NE_S'].sort_values('shape_pt_sequence')
kempscreek_NE_S_from = kempscreek_NE_S_from.reset_index(drop=True)
kempscreek_NE_S_from['shape_pt_sequence'] = kempscreek_NE_S_from.index+1
kempscreek_NE_S_from['shape_id'] = 'KempsCreek-NE-S-from'

kempscreek_NE_W_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NE_W'].sort_values('shape_pt_sequence')
kempscreek_NE_W_to = kempscreek_NE_W_to.reset_index(drop=True)
kempscreek_NE_W_to['shape_pt_sequence'] = kempscreek_NE_W_to.index+1
kempscreek_NE_W_to['shape_id'] = 'KempsCreek-NE-W-to'

kempscreek_NE_W_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NE_W'].sort_values('shape_pt_sequence')
kempscreek_NE_W_from = kempscreek_NE_W_from.reset_index(drop=True)
kempscreek_NE_W_from['shape_pt_sequence'] = kempscreek_NE_W_from.index+1
kempscreek_NE_W_from['shape_id'] = 'KempsCreek-NE-W-from'

kempscreek_NE = kempscreek_NE_E_to.append(kempscreek_NE_N_to).append(kempscreek_NE_S_to).append(kempscreek_NE_W_to).append(kempscreek_NE_E_from).append(kempscreek_NE_N_from).append(kempscreek_NE_S_from).append(kempscreek_NE_W_from)
kempscreek_NE

                shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     KempsCreek-NE-E-to    -33.894940    150.938522                  1
1     KempsCreek-NE-E-to    -33.895173    150.938475                  2
2     KempsCreek-NE-E-to    -33.895390    150.938434                  3
3     KempsCreek-NE-E-to    -33.895391    150.938327                  4
4     KempsCreek-NE-E-to    -33.895336    150.937808                  5
..                   ...           ...           ...                ...
20  KempsCreek-NE-W-from    -33.886510    150.760715                 21
21  KempsCreek-NE-W-from    -33.885733    150.754297                 22
22  KempsCreek-NE-W-from    -33.883715    150.743762                 23
23  KempsCreek-NE-W-from    -33.881450    150.741766                 24
24  KempsCreek-NE-W-from    -33.884682    150.736319                 25

[1135 rows x 4 columns]

In [34]:
# KempsCreek SW
 
kempscreek_SW_E_to = routeshapes.loc[routeshapes['shape_id']=='TT-2056-austral'].sort_values('shape_pt_sequence')
kempscreek_SW_E_to = kempscreek_SW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SW_E'].sort_values('shape_pt_sequence'))
kempscreek_SW_E_to = kempscreek_SW_E_to.reset_index(drop=True)
kempscreek_SW_E_to['shape_pt_sequence'] = kempscreek_SW_E_to.index+1
kempscreek_SW_E_to['shape_id'] = 'KempsCreek-SW-E-to'

kempscreek_SW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SW_E'].sort_values('shape_pt_sequence')
kempscreek_SW_E_from = kempscreek_SW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='TT_r-2056-austral'].sort_values('shape_pt_sequence'))
kempscreek_SW_E_from = kempscreek_SW_E_from.reset_index(drop=True)
kempscreek_SW_E_from['shape_pt_sequence'] = kempscreek_SW_E_from.index+1
kempscreek_SW_E_from['shape_id'] = 'KempsCreek-SW-E-from'

kempscreek_SW_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromStMarys'].sort_values('shape_pt_sequence')
kempscreek_SW_N_to = kempscreek_SW_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SW_N'].sort_values('shape_pt_sequence'))
kempscreek_SW_N_to = kempscreek_SW_N_to.reset_index(drop=True)
kempscreek_SW_N_to['shape_pt_sequence'] = kempscreek_SW_N_to.index+1
kempscreek_SW_N_to['shape_id'] = 'KempsCreek-SW-N-to'

kempscreek_SW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SW_N'].sort_values('shape_pt_sequence')
kempscreek_SW_N_from = kempscreek_SW_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToStMarys'].sort_values('shape_pt_sequence'))
kempscreek_SW_N_from = kempscreek_SW_N_from.reset_index(drop=True)
kempscreek_SW_N_from['shape_pt_sequence'] = kempscreek_SW_N_from.index+1
kempscreek_SW_N_from['shape_id'] = 'KempsCreek-SW-N-from'

kempscreek_SW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SW_S'].sort_values('shape_pt_sequence')
kempscreek_SW_S_to = kempscreek_SW_S_to.reset_index(drop=True)
kempscreek_SW_S_to['shape_pt_sequence'] = kempscreek_SW_S_to.index+1
kempscreek_SW_S_to['shape_id'] = 'KempsCreek-SW-S-to'

kempscreek_SW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SW_S'].sort_values('shape_pt_sequence')
kempscreek_SW_S_from = kempscreek_SW_S_from.reset_index(drop=True)
kempscreek_SW_S_from['shape_pt_sequence'] = kempscreek_SW_S_from.index+1
kempscreek_SW_S_from['shape_id'] = 'KempsCreek-SW-S-from'

kempscreek_SW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_SW_W'].sort_values('shape_pt_sequence')
kempscreek_SW_W_to = kempscreek_SW_W_to.reset_index(drop=True)
kempscreek_SW_W_to['shape_pt_sequence'] = kempscreek_SW_W_to.index+1
kempscreek_SW_W_to['shape_id'] = 'KempsCreek-SW-W-to'

kempscreek_SW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_SW_W'].sort_values('shape_pt_sequence')
kempscreek_SW_W_from = kempscreek_SW_W_from.reset_index(drop=True)
kempscreek_SW_W_from['shape_pt_sequence'] = kempscreek_SW_W_from.index+1
kempscreek_SW_W_from['shape_id'] = 'KempsCreek-SW-W-from'

kempscreek_SW = kempscreek_SW_E_to.append(kempscreek_SW_N_to).append(kempscreek_SW_S_to).append(kempscreek_SW_W_to).append(kempscreek_SW_E_from).append(kempscreek_SW_N_from).append(kempscreek_SW_S_from).append(kempscreek_SW_W_from)
kempscreek_SW

                shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     KempsCreek-SW-E-to    -33.922966    150.926880                  1
1     KempsCreek-SW-E-to    -33.922761    150.925374                  2
2     KempsCreek-SW-E-to    -33.922714    150.925022                  3
3     KempsCreek-SW-E-to    -33.922697    150.924901                  4
4     KempsCreek-SW-E-to    -33.922544    150.923725                  5
..                   ...           ...           ...                ...
14  KempsCreek-SW-W-from    -33.903982    150.747026                 15
15  KempsCreek-SW-W-from    -33.904311    150.747155                 16
16  KempsCreek-SW-W-from    -33.915873    150.744865                 17
17  KempsCreek-SW-W-from    -33.914919    150.737929                 18
18  KempsCreek-SW-W-from    -33.920700    150.736783                 19

[935 rows x 4 columns]

In [35]:
# KempsCreek NW
 
kempscreek_NW_E_to = routeshapes.loc[routeshapes['shape_id']=='25thAv-Cabramatta-ElizabethDrive'].sort_values('shape_pt_sequence')
kempscreek_NW_E_to = kempscreek_NW_E_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NW_E'].sort_values('shape_pt_sequence'))
kempscreek_NW_E_to = kempscreek_NW_E_to.reset_index(drop=True)
kempscreek_NW_E_to['shape_pt_sequence'] = kempscreek_NW_E_to.index+1
kempscreek_NW_E_to['shape_id'] = 'KempsCreek-NW-E-to'

kempscreek_NW_E_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NW_E'].sort_values('shape_pt_sequence')
kempscreek_NW_E_from = kempscreek_NW_E_from.append(routeshapes.loc[routeshapes['shape_id']=='25thAv-ElizabethDrive-Cabramatta'].sort_values('shape_pt_sequence'))
kempscreek_NW_E_from = kempscreek_NW_E_from.reset_index(drop=True)
kempscreek_NW_E_from['shape_pt_sequence'] = kempscreek_NW_E_from.index+1
kempscreek_NW_E_from['shape_id'] = 'KempsCreek-NW-E-from'

kempscreek_NW_N_to = routeshapes.loc[routeshapes['shape_id']=='Connection-FromStMarys'].sort_values('shape_pt_sequence')
kempscreek_NW_N_to = kempscreek_NW_N_to.append(routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NW_N'].sort_values('shape_pt_sequence'))
kempscreek_NW_N_to = kempscreek_NW_N_to.reset_index(drop=True)
kempscreek_NW_N_to['shape_pt_sequence'] = kempscreek_NW_N_to.index+1
kempscreek_NW_N_to['shape_id'] = 'KempsCreek-NW-N-to'

kempscreek_NW_N_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NW_N'].sort_values('shape_pt_sequence')
kempscreek_NW_N_from = kempscreek_NW_N_from.append(routeshapes.loc[routeshapes['shape_id']=='Connection-ToStMarys'].sort_values('shape_pt_sequence'))
kempscreek_NW_N_from = kempscreek_NW_N_from.reset_index(drop=True)
kempscreek_NW_N_from['shape_pt_sequence'] = kempscreek_NW_N_from.index+1
kempscreek_NW_N_from['shape_id'] = 'KempsCreek-NW-N-from'

kempscreek_NW_S_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NW_S'].sort_values('shape_pt_sequence')
kempscreek_NW_S_to = kempscreek_NW_S_to.reset_index(drop=True)
kempscreek_NW_S_to['shape_pt_sequence'] = kempscreek_NW_S_to.index+1
kempscreek_NW_S_to['shape_id'] = 'KempsCreek-NW-S-to'

kempscreek_NW_S_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NW_S'].sort_values('shape_pt_sequence')
kempscreek_NW_S_from = kempscreek_NW_S_from.reset_index(drop=True)
kempscreek_NW_S_from['shape_pt_sequence'] = kempscreek_NW_S_from.index+1
kempscreek_NW_S_from['shape_id'] = 'KempsCreek-NW-S-from'

kempscreek_NW_W_to = routeshapes.loc[routeshapes['shape_id']=='To_KempsCreek_NW_W'].sort_values('shape_pt_sequence')
kempscreek_NW_W_to = kempscreek_NW_W_to.reset_index(drop=True)
kempscreek_NW_W_to['shape_pt_sequence'] = kempscreek_NW_W_to.index+1
kempscreek_NW_W_to['shape_id'] = 'KempsCreek-NW-W-to'

kempscreek_NW_W_from = routeshapes.loc[routeshapes['shape_id']=='From_KempsCreek_NW_W'].sort_values('shape_pt_sequence')
kempscreek_NW_W_from = kempscreek_NW_W_from.reset_index(drop=True)
kempscreek_NW_W_from['shape_pt_sequence'] = kempscreek_NW_W_from.index+1
kempscreek_NW_W_from['shape_id'] = 'KempsCreek-NW-W-from'

kempscreek_NW = kempscreek_NW_E_to.append(kempscreek_NW_N_to).append(kempscreek_NW_S_to).append(kempscreek_NW_W_to).append(kempscreek_NW_E_from).append(kempscreek_NW_N_from).append(kempscreek_NW_S_from).append(kempscreek_NW_W_from)
kempscreek_NW

                shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0     KempsCreek-NW-E-to    -33.894940    150.938522                  1
1     KempsCreek-NW-E-to    -33.895173    150.938475                  2
2     KempsCreek-NW-E-to    -33.895390    150.938434                  3
3     KempsCreek-NW-E-to    -33.895391    150.938327                  4
4     KempsCreek-NW-E-to    -33.895336    150.937808                  5
..                   ...           ...           ...                ...
19  KempsCreek-NW-W-from    -33.886510    150.760715                 20
20  KempsCreek-NW-W-from    -33.885733    150.754297                 21
21  KempsCreek-NW-W-from    -33.883715    150.743762                 22
22  KempsCreek-NW-W-from    -33.881450    150.741766                 23
23  KempsCreek-NW-W-from    -33.884682    150.736319                 24

[961 rows x 4 columns]

In [36]:
localroutesforstops = austral_NE_N_to.append(austral_NE_E_to).append(austral_NE_W_to).append(austral_NE_S_to)
localroutesforstops = localroutesforstops.append(austral_NW_N_to).append(austral_NW_E_to).append(austral_NW_W_to).append(austral_NW_S_to)
localroutesforstops = localroutesforstops.append(austral_SE_N_to).append(austral_SE_E_to).append(austral_SE_W_to).append(austral_SE_S_to)
localroutesforstops = localroutesforstops.append(austral_SW_N_to).append(austral_SW_E_to).append(austral_SW_W_to).append(austral_SW_S_to)
localroutesforstops = localroutesforstops.append(rossmore_NE_N_to).append(rossmore_NE_E_to).append(rossmore_NE_W_to).append(rossmore_NE_S_to)
localroutesforstops = localroutesforstops.append(rossmore_NW_N_to).append(rossmore_NW_E_to).append(rossmore_NW_W_to).append(rossmore_NW_S_to)
localroutesforstops = localroutesforstops.append(rossmore_SE_N_to).append(rossmore_SE_E_to).append(rossmore_SE_W_to).append(rossmore_SE_S_to)
localroutesforstops = localroutesforstops.append(rossmore_SW_N_to).append(rossmore_SW_E_to).append(rossmore_SW_W_to).append(rossmore_SW_S_to)
localroutesforstops = localroutesforstops.append(kempscreek_NE_N_to).append(kempscreek_NE_E_to).append(kempscreek_NE_W_to).append(kempscreek_NE_S_to)
localroutesforstops = localroutesforstops.append(kempscreek_NW_N_to).append(kempscreek_NW_E_to).append(kempscreek_NW_W_to).append(kempscreek_NW_S_to)
localroutesforstops = localroutesforstops.append(kempscreek_SE_N_to).append(kempscreek_SE_E_to).append(kempscreek_SE_W_to).append(kempscreek_SE_S_to)
localroutesforstops = localroutesforstops.append(kempscreek_SW_N_to).append(kempscreek_SW_E_to).append(kempscreek_SW_W_to).append(kempscreek_SW_S_to)
localroutesforstops = localroutesforstops.append(austral_NE_N_from).append(austral_NE_E_from).append(austral_NE_W_from).append(austral_NE_S_from)
localroutesforstops = localroutesforstops.append(austral_NW_N_from).append(austral_NW_E_from).append(austral_NW_W_from).append(austral_NW_S_from)
localroutesforstops = localroutesforstops.append(austral_SE_N_from).append(austral_SE_E_from).append(austral_SE_W_from).append(austral_SE_S_from)
localroutesforstops = localroutesforstops.append(austral_SW_N_from).append(austral_SW_E_from).append(austral_SW_W_from).append(austral_SW_S_from)
localroutesforstops = localroutesforstops.append(rossmore_NE_N_from).append(rossmore_NE_E_from).append(rossmore_NE_W_from).append(rossmore_NE_S_from)
localroutesforstops = localroutesforstops.append(rossmore_NW_N_from).append(rossmore_NW_E_from).append(rossmore_NW_W_from).append(rossmore_NW_S_from)
localroutesforstops = localroutesforstops.append(rossmore_SE_N_from).append(rossmore_SE_E_from).append(rossmore_SE_W_from).append(rossmore_SE_S_from)
localroutesforstops = localroutesforstops.append(rossmore_SW_N_from).append(rossmore_SW_E_from).append(rossmore_SW_W_from).append(rossmore_SW_S_from)
localroutesforstops = localroutesforstops.append(kempscreek_NE_N_from).append(kempscreek_NE_E_from).append(kempscreek_NE_W_from).append(kempscreek_NE_S_from)
localroutesforstops = localroutesforstops.append(kempscreek_NW_N_from).append(kempscreek_NW_E_from).append(kempscreek_NW_W_from).append(kempscreek_NW_S_from)
localroutesforstops = localroutesforstops.append(kempscreek_SE_N_from).append(kempscreek_SE_E_from).append(kempscreek_SE_W_from).append(kempscreek_SE_S_from)
localroutesforstops = localroutesforstops.append(kempscreek_SW_N_from).append(kempscreek_SW_E_from).append(kempscreek_SW_W_from).append(kempscreek_SW_S_from)
localroutesforstops = localroutesforstops.reset_index(drop=True)
localroutesforstops.head()

          shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0  Austral-NE-N-to    -33.884682    150.736319                  1
1  Austral-NE-N-to    -33.881450    150.741766                  2
2  Austral-NE-N-to    -33.883715    150.743762                  3
3  Austral-NE-N-to    -33.885733    150.754297                  4
4  Austral-NE-N-to    -33.885830    150.755099                  5

### Middleton Grange route(s)

In [37]:
# Middleton Grange to Aerotropolis

mg_aero = routeshapes.loc[routeshapes['shape_id']=='MG_FAST_TOD'].sort_values('shape_pt_sequence')
mg_aero = mg_aero.append(routeshapes.loc[routeshapes['shape_id']=='FAST_Aerotropolis'].sort_values('shape_pt_sequence'))
mg_aero = mg_aero.reset_index(drop=True)
mg_aero['shape_pt_sequence'] = mg_aero.index+1
mg_aero['shape_id'] = 'MG-AERO'

aero_mg = routeshapes.loc[routeshapes['shape_id']=='Aerotropolis_FAST'].sort_values('shape_pt_sequence')
aero_mg = aero_mg.append(routeshapes.loc[routeshapes['shape_id']=='FAST_MG_TOD'].sort_values('shape_pt_sequence'))
aero_mg = aero_mg.reset_index(drop=True)
aero_mg['shape_pt_sequence'] = aero_mg.index+1
aero_mg['shape_id'] = 'AERO-MG'

mgAeroRoutes = mg_aero.append(aero_mg, ignore_index=True)
mgAeroRoutes

    shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0    MG-AERO    -33.918486    150.845747                  1
1    MG-AERO    -33.918447    150.845242                  2
2    MG-AERO    -33.918383    150.844825                  3
3    MG-AERO    -33.918253    150.843972                  4
4    MG-AERO    -33.918160    150.843286                  5
..       ...           ...           ...                ...
373  AERO-MG    -33.918160    150.843286                159
374  AERO-MG    -33.918253    150.843972                160
375  AERO-MG    -33.918383    150.844825                161
376  AERO-MG    -33.918447    150.845242                162
377  AERO-MG    -33.918486    150.845747                163

[378 rows x 4 columns]

### Combine routes for stops

In [38]:
print(len(futureTways))
print(len(localroutesforstops))
print(len(mgAeroRoutes))
futureshapesforstops = futureTways.append(localroutesforstops, ignore_index=True).append(mgAeroRoutes, ignore_index=True)
print(len(futureshapesforstops))

4010
12895
378
17283

In [39]:
futureshapesforstops = futureshapesforstops.sort_values(['shape_id','shape_pt_sequence'], ascending=[True,True]).reset_index(drop=True)
futureshapesforstops['geopy_dist'] = np.nan
for i in range(len(futureshapesforstops)):
    if futureshapesforstops['shape_pt_sequence'][i] == 1:
        futureshapesforstops['geopy_dist'][i] = 0
    else:
        p1 = (futureshapesforstops['shape_pt_lat'][i-1],futureshapesforstops['shape_pt_lon'][i-1]) 
        p2 = (futureshapesforstops['shape_pt_lat'][i],futureshapesforstops['shape_pt_lon'][i])
        futureshapesforstops['geopy_dist'][i] = geo.sphere.haversine_distance(p1,p2)
futureshapesforstops['cum_dist'] = futureshapesforstops.groupby(['shape_id'])['geopy_dist'].cumsum()
futureshapesforstops.head()

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,geopy_dist,cum_dist
0,10th-ASTH-CSLA,-33.934464,150.740443,1,0.000000,0.000000
1,10th-ASTH-CSLA,-33.934563,150.741161,2,80.402344,80.402344
2,10th-ASTH-CSLA,-33.933217,150.741428,3,133.938825,214.341169
3,10th-ASTH-CSLA,-33.931870,150.741695,4,133.939030,348.280199
4,10th-ASTH-CSLA,-33.930564,150.741953,5,129.937671,478.217869

In [40]:
futureshapesforstops.drop('geopy_dist', axis=1, inplace=True)
futureshapesforstops.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence','shape_dist_traveled']
futureshapesforstops.head()

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10th-ASTH-CSLA,-33.934464,150.740443,1,0.000000
1,10th-ASTH-CSLA,-33.934563,150.741161,2,80.402344
2,10th-ASTH-CSLA,-33.933217,150.741428,3,214.341169
3,10th-ASTH-CSLA,-33.931870,150.741695,4,348.280199
4,10th-ASTH-CSLA,-33.930564,150.741953,5,478.217869

In [41]:
futureshapesforstops.to_csv('./Shapes/twayLocalRouteShapes_forStops_1TOD.csv', index=False)

### Combine local routes to and from and append tway routes for shapes.txt

In [42]:
# Austral

austral_NE_E = austral_NE_E_to.append(austral_NE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NE_E['shape_pt_sequence'] = austral_NE_E.index+1
austral_NE_E['shape_id'] = 'Austral-NE-E'

austral_NE_N = austral_NE_N_to.append(austral_NE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NE_N['shape_pt_sequence'] = austral_NE_N.index+1
austral_NE_N['shape_id'] = 'Austral-NE-N'

austral_NE_S = austral_NE_S_to.append(austral_NE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NE_S['shape_pt_sequence'] = austral_NE_S.index+1
austral_NE_S['shape_id'] = 'Austral-NE-S'

austral_NE_W = austral_NE_W_to.append(austral_NE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NE_W['shape_pt_sequence'] = austral_NE_W.index+1
austral_NE_W['shape_id'] = 'Austral-NE-W'

austral_NW_E = austral_NW_E_to.append(austral_NW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NW_E['shape_pt_sequence'] = austral_NW_E.index+1
austral_NW_E['shape_id'] = 'Austral-NW-E'

austral_NW_N = austral_NW_N_to.append(austral_NW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NW_N['shape_pt_sequence'] = austral_NW_N.index+1
austral_NW_N['shape_id'] = 'Austral-NW-N'

austral_NW_S = austral_NW_S_to.append(austral_NW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NW_S['shape_pt_sequence'] = austral_NW_S.index+1
austral_NW_S['shape_id'] = 'Austral-NW-S'

austral_NW_W = austral_NW_W_to.append(austral_NW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_NW_W['shape_pt_sequence'] = austral_NW_W.index+1
austral_NW_W['shape_id'] = 'Austral-NW-W'

austral_SE_E = austral_SE_E_to.append(austral_SE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SE_E['shape_pt_sequence'] = austral_SE_E.index+1
austral_SE_E['shape_id'] = 'Austral-SE-E'

austral_SE_N = austral_SE_N_to.append(austral_SE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SE_N['shape_pt_sequence'] = austral_SE_N.index+1
austral_SE_N['shape_id'] = 'Austral-SE-N'

austral_SE_S = austral_SE_S_to.append(austral_SE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SE_S['shape_pt_sequence'] = austral_SE_S.index+1
austral_SE_S['shape_id'] = 'Austral-SE-S'

austral_SE_W = austral_SE_W_to.append(austral_SE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SE_W['shape_pt_sequence'] = austral_SE_W.index+1
austral_SE_W['shape_id'] = 'Austral-SE-W'

austral_SW_E = austral_SW_E_to.append(austral_SW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SW_E['shape_pt_sequence'] = austral_SW_E.index+1
austral_SW_E['shape_id'] = 'Austral-SW-E'

austral_SW_N = austral_SW_N_to.append(austral_SW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SW_N['shape_pt_sequence'] = austral_SW_N.index+1
austral_SW_N['shape_id'] = 'Austral-SW-N'

austral_SW_S = austral_SW_S_to.append(austral_SW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SW_S['shape_pt_sequence'] = austral_SW_S.index+1
austral_SW_S['shape_id'] = 'Austral-SW-S'

austral_SW_W = austral_SW_W_to.append(austral_SW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
austral_SW_W['shape_pt_sequence'] = austral_SW_W.index+1
austral_SW_W['shape_id'] = 'Austral-SW-W'

In [43]:
# Rossmore

rossmore_NE_E = rossmore_NE_E_to.append(rossmore_NE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NE_E['shape_pt_sequence'] = rossmore_NE_E.index+1
rossmore_NE_E['shape_id'] = 'Rossmore-NE-E'

rossmore_NE_N = rossmore_NE_N_to.append(rossmore_NE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NE_N['shape_pt_sequence'] = rossmore_NE_N.index+1
rossmore_NE_N['shape_id'] = 'Rossmore-NE-N'

rossmore_NE_S = rossmore_NE_S_to.append(rossmore_NE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NE_S['shape_pt_sequence'] = rossmore_NE_S.index+1
rossmore_NE_S['shape_id'] = 'Rossmore-NE-S'

rossmore_NE_W = rossmore_NE_W_to.append(rossmore_NE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NE_W['shape_pt_sequence'] = rossmore_NE_W.index+1
rossmore_NE_W['shape_id'] = 'Rossmore-NE-W'

rossmore_NW_E = rossmore_NW_E_to.append(rossmore_NW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NW_E['shape_pt_sequence'] = rossmore_NW_E.index+1
rossmore_NW_E['shape_id'] = 'Rossmore-NW-E'

rossmore_NW_N = rossmore_NW_N_to.append(rossmore_NW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NW_N['shape_pt_sequence'] = rossmore_NW_N.index+1
rossmore_NW_N['shape_id'] = 'Rossmore-NW-N'

rossmore_NW_S = rossmore_NW_S_to.append(rossmore_NW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NW_S['shape_pt_sequence'] = rossmore_NW_S.index+1
rossmore_NW_S['shape_id'] = 'Rossmore-NW-S'

rossmore_NW_W = rossmore_NW_W_to.append(rossmore_NW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_NW_W['shape_pt_sequence'] = rossmore_NW_W.index+1
rossmore_NW_W['shape_id'] = 'Rossmore-NW-W'

rossmore_SE_E = rossmore_SE_E_to.append(rossmore_SE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SE_E['shape_pt_sequence'] = rossmore_SE_E.index+1
rossmore_SE_E['shape_id'] = 'Rossmore-SE-E'

rossmore_SE_N = rossmore_SE_N_to.append(rossmore_SE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SE_N['shape_pt_sequence'] = rossmore_SE_N.index+1
rossmore_SE_N['shape_id'] = 'Rossmore-SE-N'

rossmore_SE_S = rossmore_SE_S_to.append(rossmore_SE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SE_S['shape_pt_sequence'] = rossmore_SE_S.index+1
rossmore_SE_S['shape_id'] = 'Rossmore-SE-S'

rossmore_SE_W = rossmore_SE_W_to.append(rossmore_SE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SE_W['shape_pt_sequence'] = rossmore_SE_W.index+1
rossmore_SE_W['shape_id'] = 'Rossmore-SE-W'

rossmore_SW_E = rossmore_SW_E_to.append(rossmore_SW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SW_E['shape_pt_sequence'] = rossmore_SW_E.index+1
rossmore_SW_E['shape_id'] = 'Rossmore-SW-E'

rossmore_SW_N = rossmore_SW_N_to.append(rossmore_SW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SW_N['shape_pt_sequence'] = rossmore_SW_N.index+1
rossmore_SW_N['shape_id'] = 'Rossmore-SW-N'

rossmore_SW_S = rossmore_SW_S_to.append(rossmore_SW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SW_S['shape_pt_sequence'] = rossmore_SW_S.index+1
rossmore_SW_S['shape_id'] = 'Rossmore-SW-S'

rossmore_SW_W = rossmore_SW_W_to.append(rossmore_SW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
rossmore_SW_W['shape_pt_sequence'] = rossmore_SW_W.index+1
rossmore_SW_W['shape_id'] = 'Rossmore-SW-W'

In [44]:
# Kempscreek

kempscreek_NE_E = kempscreek_NE_E_to.append(kempscreek_NE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NE_E['shape_pt_sequence'] = kempscreek_NE_E.index+1
kempscreek_NE_E['shape_id'] = 'KempsCreek-NE-E'

kempscreek_NE_N = kempscreek_NE_N_to.append(kempscreek_NE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NE_N['shape_pt_sequence'] = kempscreek_NE_N.index+1
kempscreek_NE_N['shape_id'] = 'KempsCreek-NE-N'

kempscreek_NE_S = kempscreek_NE_S_to.append(kempscreek_NE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NE_S['shape_pt_sequence'] = kempscreek_NE_S.index+1
kempscreek_NE_S['shape_id'] = 'KempsCreek-NE-S'

kempscreek_NE_W = kempscreek_NE_W_to.append(kempscreek_NE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NE_W['shape_pt_sequence'] = kempscreek_NE_W.index+1
kempscreek_NE_W['shape_id'] = 'KempsCreek-NE-W'

kempscreek_NW_E = kempscreek_NW_E_to.append(kempscreek_NW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NW_E['shape_pt_sequence'] = kempscreek_NW_E.index+1
kempscreek_NW_E['shape_id'] = 'KempsCreek-NW-E'

kempscreek_NW_N = kempscreek_NW_N_to.append(kempscreek_NW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NW_N['shape_pt_sequence'] = kempscreek_NW_N.index+1
kempscreek_NW_N['shape_id'] = 'KempsCreek-NW-N'

kempscreek_NW_S = kempscreek_NW_S_to.append(kempscreek_NW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NW_S['shape_pt_sequence'] = kempscreek_NW_S.index+1
kempscreek_NW_S['shape_id'] = 'KempsCreek-NW-S'

kempscreek_NW_W = kempscreek_NW_W_to.append(kempscreek_NW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_NW_W['shape_pt_sequence'] = kempscreek_NW_W.index+1
kempscreek_NW_W['shape_id'] = 'KempsCreek-NW-W'

kempscreek_SE_E = kempscreek_SE_E_to.append(kempscreek_SE_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SE_E['shape_pt_sequence'] = kempscreek_SE_E.index+1
kempscreek_SE_E['shape_id'] = 'KempsCreek-SE-E'

kempscreek_SE_N = kempscreek_SE_N_to.append(kempscreek_SE_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SE_N['shape_pt_sequence'] = kempscreek_SE_N.index+1
kempscreek_SE_N['shape_id'] = 'KempsCreek-SE-N'

kempscreek_SE_S = kempscreek_SE_S_to.append(kempscreek_SE_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SE_S['shape_pt_sequence'] = kempscreek_SE_S.index+1
kempscreek_SE_S['shape_id'] = 'KempsCreek-SE-S'

kempscreek_SE_W = kempscreek_SE_W_to.append(kempscreek_SE_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SE_W['shape_pt_sequence'] = kempscreek_SE_W.index+1
kempscreek_SE_W['shape_id'] = 'KempsCreek-SE-W'

kempscreek_SW_E = kempscreek_SW_E_to.append(kempscreek_SW_E_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SW_E['shape_pt_sequence'] = kempscreek_SW_E.index+1
kempscreek_SW_E['shape_id'] = 'KempsCreek-SW-E'

kempscreek_SW_N = kempscreek_SW_N_to.append(kempscreek_SW_N_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SW_N['shape_pt_sequence'] = kempscreek_SW_N.index+1
kempscreek_SW_N['shape_id'] = 'KempsCreek-SW-N'

kempscreek_SW_S = kempscreek_SW_S_to.append(kempscreek_SW_S_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SW_S['shape_pt_sequence'] = kempscreek_SW_S.index+1
kempscreek_SW_S['shape_id'] = 'KempsCreek-SW-S'

kempscreek_SW_W = kempscreek_SW_W_to.append(kempscreek_SW_W_from.sort_values('shape_pt_sequence'), ignore_index=True)
kempscreek_SW_W['shape_pt_sequence'] = kempscreek_SW_W.index+1
kempscreek_SW_W['shape_id'] = 'KempsCreek-SW-W'

In [45]:
futurelocalroutes = austral_NE_E.append(austral_NE_N).append(austral_NE_S).append(austral_NE_W)
futurelocalroutes = futurelocalroutes.append(austral_NW_E).append(austral_NW_N).append(austral_NW_S).append(austral_NW_W)
futurelocalroutes = futurelocalroutes.append(austral_SE_E).append(austral_SE_N).append(austral_SE_S).append(austral_SE_W)
futurelocalroutes = futurelocalroutes.append(austral_SW_E).append(austral_SW_N).append(austral_SW_S).append(austral_SW_W)
futurelocalroutes = futurelocalroutes.append(rossmore_NE_E).append(rossmore_NE_N).append(rossmore_NE_S).append(rossmore_NE_W)
futurelocalroutes = futurelocalroutes.append(rossmore_NW_E).append(rossmore_NW_N).append(rossmore_NW_S).append(rossmore_NW_W)
futurelocalroutes = futurelocalroutes.append(rossmore_SE_E).append(rossmore_SE_N).append(rossmore_SE_S).append(rossmore_SE_W)
futurelocalroutes = futurelocalroutes.append(rossmore_SW_E).append(rossmore_SW_N).append(rossmore_SW_S).append(rossmore_SW_W)
futurelocalroutes = futurelocalroutes.append(kempscreek_NE_E).append(kempscreek_NE_N).append(kempscreek_NE_S).append(kempscreek_NE_W)
futurelocalroutes = futurelocalroutes.append(kempscreek_NW_E).append(kempscreek_NW_N).append(kempscreek_NW_S).append(kempscreek_NW_W)
futurelocalroutes = futurelocalroutes.append(kempscreek_SE_E).append(kempscreek_SE_N).append(kempscreek_SE_S).append(kempscreek_SE_W)
futurelocalroutes = futurelocalroutes.append(kempscreek_SW_E).append(kempscreek_SW_N).append(kempscreek_SW_S).append(kempscreek_SW_W)
futurelocalroutes = futurelocalroutes.reset_index(drop=True)
futurelocalroutes.head()

       shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0  Austral-NE-E    -33.922966    150.926880                  1
1  Austral-NE-E    -33.922761    150.925374                  2
2  Austral-NE-E    -33.922714    150.925022                  3
3  Austral-NE-E    -33.922697    150.924901                  4
4  Austral-NE-E    -33.922544    150.923725                  5

In [46]:
print(len(futureTways))
print(len(futurelocalroutes))
print(len(mgAeroRoutes))
futureshapes = futureTways.append(futurelocalroutes, ignore_index=True).append(mgAeroRoutes, ignore_index=True)
print(len(futureshapes))

4010
12895
378
17283

In [47]:
futureshapes = futureshapes.sort_values(['shape_id','shape_pt_sequence'], ascending=[True,True]).reset_index(drop=True)
futureshapes['geopy_dist'] = np.nan
for i in range(len(futureshapes)):
    if futureshapes['shape_pt_sequence'][i] == 1:
        futureshapes['geopy_dist'][i] = 0
    else:
        p1 = (futureshapes['shape_pt_lat'][i-1],futureshapes['shape_pt_lon'][i-1]) 
        p2 = (futureshapes['shape_pt_lat'][i],futureshapes['shape_pt_lon'][i])
        futureshapes['geopy_dist'][i] = geo.sphere.haversine_distance(p1,p2)
futureshapes['cum_dist'] = futureshapes.groupby(['shape_id'])['geopy_dist'].cumsum()
futureshapes.head()

/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/hemarayaprolu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,geopy_dist,cum_dist
0,10th-ASTH-CSLA,-33.934464,150.740443,1,0.000000,0.000000
1,10th-ASTH-CSLA,-33.934563,150.741161,2,80.402344,80.402344
2,10th-ASTH-CSLA,-33.933217,150.741428,3,133.938825,214.341169
3,10th-ASTH-CSLA,-33.931870,150.741695,4,133.939030,348.280199
4,10th-ASTH-CSLA,-33.930564,150.741953,5,129.937671,478.217869

In [48]:
futureshapes.drop('geopy_dist', axis=1, inplace=True)
futureshapes.columns = ['shape_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence','shape_dist_traveled']
futureshapes.head()

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10th-ASTH-CSLA,-33.934464,150.740443,1,0.000000
1,10th-ASTH-CSLA,-33.934563,150.741161,2,80.402344
2,10th-ASTH-CSLA,-33.933217,150.741428,3,214.341169
3,10th-ASTH-CSLA,-33.931870,150.741695,4,348.280199
4,10th-ASTH-CSLA,-33.930564,150.741953,5,478.217869

In [49]:
futureshapes.to_csv('./output/future/road/1TOD/shapes.txt', index=False)