In [1]:
import pandas as pd
import numpy as np

In [3]:
stops = pd.read_csv('./Stops/stopsTwaysLocalRoutes_TOD14.csv')
mgstops = pd.read_csv('./Stops/MiddletonGrangeStops.csv')
stopsByRoute = pd.read_csv('./Stops/StopsByRoute_TwayLocalRotues_TOD14.csv')

### Merge stops and stops by route to get distance along route (from QGIS)

In [4]:
stops.head()

       stop_name   stop_lat    stop_lon    stop_id
0  Austral-NE-1a -33.923423  150.811590  202008141
1  Austral-NE-1b -33.923410  150.811614  202008142
2  Austral-NE-2a -33.920224  150.809679  202008143
3  Austral-NE-2b -33.920206  150.809714  202008144
4  Austral-NE-3a -33.915365  150.810117  202008145

In [5]:
len(stops)

360

In [6]:
mgstops.head()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_t,parent_sta,wheelchair,platform_c,mode,route
0,2171432,2171432.0,"Inspire Church, Hoxton Park Rd",-33.926348,150.867140,NaN,NaN,0.0,NaN,Bus,NaN
1,2170481,2170481.0,Macquarie St At Short St,-33.927885,150.918795,NaN,NaN,0.0,NaN,Bus,NaN
2,2170480,2170480.0,"Woodward Park, Hoxton Park Rd",-33.928155,150.912840,NaN,NaN,0.0,NaN,Bus,NaN
3,217493,217493.0,Bernera Rd Opp Poziers Rd,-33.963460,150.861305,NaN,NaN,0.0,NaN,Bus,NaN
4,2168258,2168258.0,Cowpasture Rd After Collarenebri Rd,-33.921516,150.850545,NaN,NaN,0.0,NaN,Bus,NaN

In [7]:
len(mgstops)

149

In [8]:
mgstops = mgstops[['stop_id','stop_name','stop_lat','stop_lon']]
stops = stops.append(mgstops, ignore_index=True)
stops.head()

       stop_name   stop_lat    stop_lon    stop_id
0  Austral-NE-1a -33.923423  150.811590  202008141
1  Austral-NE-1b -33.923410  150.811614  202008142
2  Austral-NE-2a -33.920224  150.809679  202008143
3  Austral-NE-2b -33.920206  150.809714  202008144
4  Austral-NE-3a -33.915365  150.810117  202008145

In [9]:
len(stops)

509

In [10]:
stopsByRoute.head()

         shape_id  begin  end      stop_id
0  10th-ASTH-CSLA      1  427  20200814198
1  10th-ASTH-CSLA      1  427  20200814202
2  10th-ASTH-CSLA      1  427  20200814210
3  10th-ASTH-CSLA      1  427  20200814214
4  10th-ASTH-CSLA      1  427  20200814260

In [11]:
print(len(stopsByRoute))
stopsByRoute = stopsByRoute.merge(stops, how='left', on='stop_id')
print(len(stopsByRoute))

1230
1230

In [12]:
stopsByRoute.isnull().sum()

shape_id     0
begin        0
end          0
stop_id      0
stop_name    0
stop_lat     0
stop_lon     0
dtype: int64

In [13]:
stopsByRoute.to_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_TOD14.csv', index=False)

line_locate_point(geometry:=geometry(get_feature('1925_BusRoutes_Projected', 'R', "join_R")), point:=$geometry)

### Compare stops by route in each scenario

In [13]:
stopsGrid = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_Grid.csv')
stops1tod = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_1TOD.csv')
stops2tod = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_2TOD.csv')
stops3tod = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_3TOD.csv')
stops4tod = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_forDist_4TOD.csv')

In [14]:
len(stopsGrid)

1226

In [15]:
len(stops1tod)

1226

In [16]:
len(stops2tod)

1216

In [17]:
len(stops3tod)

1216

In [18]:
len(stops4tod)

1216

In [19]:
stopsGrid.head()

,shape_id,begin,end,stop_id,stop_name,stop_lat,stop_lon
0,10th-ASTH-CSLA,1,427,20200814198,Rossmore-SW-WE,-33.925766,150.769163
1,10th-ASTH-CSLA,1,427,20200814202,Rossmore-SE-WE,-33.929035,150.784891
2,10th-ASTH-CSLA,1,427,20200814210,Austral-SW-WE,-33.939123,150.797188
3,10th-ASTH-CSLA,1,427,20200814214,Austral-SE-WE,-33.933048,150.811829
4,10th-ASTH-CSLA,1,427,20200814260,10thAv_AerotropolisSouth_b,-33.934483,150.740965

In [20]:
stopsGrid = stopsGrid[['shape_id','stop_id']].groupby('shape_id',as_index=False).count()
stops1tod = stops1tod[['shape_id','stop_id']].groupby('shape_id',as_index=False).count()
stops2tod = stops2tod[['shape_id','stop_id']].groupby('shape_id',as_index=False).count()
stops3tod = stops3tod[['shape_id','stop_id']].groupby('shape_id',as_index=False).count()
stops4tod = stops4tod[['shape_id','stop_id']].groupby('shape_id',as_index=False).count()

In [21]:
stopscomp = stopsGrid.merge(stops1tod, how='left', on='shape_id', suffixes = ('_grid','_1tod'))
stopscomp = stopscomp.merge(stops2tod, how='left', on='shape_id')
stopscomp = stopscomp.merge(stops3tod, how='left', on='shape_id', suffixes = ('_2tod','_3tod'))
stopscomp = stopscomp.merge(stops4tod, how='left', on='shape_id')
stopscomp

,shape_id,stop_id_grid,stop_id_1tod,stop_id_2tod,stop_id_3tod,stop_id
0,10th-ASTH-CSLA,13,13,13,13,13
1,10th-CSLA-ASTH,13,13,13,13,13
2,15th-AERO-LVPL,13,13,13,13,13
3,15th-LVPL-AERO,13,13,13,13,13
4,20th-AERO-LVPL,14,14,14,14,14
...,...,...,...,...,...,...
109,Rossmore-SW-N-to,18,18,18,18,18
110,Rossmore-SW-S-from,5,5,5,5,5
111,Rossmore-SW-S-to,5,5,5,5,5
112,Rossmore-SW-W-from,5,5,5,5,5
113,Rossmore-SW-W-to,5,5,5,5,5

In [22]:
stopscomp.to_csv('./Stops/test.csv', index=False)

### Combine to and from route distances for local routes

First remove any stops that need to be removed (especially in Grid and 1TOD scenarios)

In [14]:
stopsseparate = pd.read_csv('./Stops/stopsByRoute_TwaysLocalRoutes_withDistAlongR_TOD14.csv')
stopsseparate.head()

,shape_id,begin,end,stop_id,stop_name,stop_lat,stop_lon,distAlongR
0,10th-ASTH-CSLA,1,427,20200814198,Rossmore-SW-WE,-33.925766,150.769163,3804.08919
1,10th-ASTH-CSLA,1,427,20200814202,Rossmore-SE-WE,-33.929035,150.784891,5446.92407
2,10th-ASTH-CSLA,1,427,20200814210,Austral-SW-WE,-33.931200,150.798671,6743.77943
3,10th-ASTH-CSLA,1,427,20200814214,Austral-SE-WE,-33.933048,150.811829,7977.77206
4,10th-ASTH-CSLA,1,427,20200814260,10thAv_AerotropolisSouth_b,-33.934483,150.740965,47.94503

In [15]:
len(stopsseparate)

1216

In [16]:
shapesforstops = pd.read_csv('./Shapes/twayLocalRouteShapes_forStops_TOD14.csv')
shapesforstops.head()

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10th-ASTH-CSLA,-33.934464,150.740443,1,0.000000
1,10th-ASTH-CSLA,-33.934563,150.741161,2,80.402344
2,10th-ASTH-CSLA,-33.933217,150.741428,3,214.341169
3,10th-ASTH-CSLA,-33.931870,150.741695,4,348.280199
4,10th-ASTH-CSLA,-33.930564,150.741953,5,478.217869

#### Get parent routes with to_route lengths

In [17]:
localroutes = shapesforstops.loc[(shapesforstops['shape_id'].str.contains('Austral')) | (shapesforstops['shape_id'].str.contains('Rossmore')) | (shapesforstops['shape_id'].str.contains('KempsCreek'))]
localroutes = localroutes[['shape_id','shape_dist_traveled']].groupby('shape_id', as_index=False).max()
len(localroutes)

96

In [18]:
localroutes['parent_route'] = localroutes['shape_id'].str.rstrip('-from').str.rstrip('-to')
localroutes.head()

            shape_id  shape_dist_traveled  parent_route
0  Austral-NE-E-from         15101.614826  Austral-NE-E
1    Austral-NE-E-to         14472.618325  Austral-NE-E
2  Austral-NE-N-from         14079.822930  Austral-NE-N
3    Austral-NE-N-to         13458.250702  Austral-NE-N
4  Austral-NE-S-from          5383.557159  Austral-NE-S

In [19]:
parentroutes = localroutes.loc[localroutes['shape_id'].str.contains('-to')].drop('shape_id',axis=1)
parentroutes.columns = ['toroute_length','parent_route']
print(len(parentroutes))
parentroutes.head()

48

   toroute_length  parent_route
1    14472.618325  Austral-NE-E
3    13458.250702  Austral-NE-N
5     5923.839748  Austral-NE-S
7    11974.395255  Austral-NE-W
9    17059.572154  Austral-NW-E

#### Separate tway and local route stops

In [20]:
stopsseparate['parent_route'] = stopsseparate['shape_id'].str.rstrip('-from').str.rstrip('-to')
stopsseparate.head()

,shape_id,begin,end,stop_id,stop_name,stop_lat,stop_lon,distAlongR,parent_route
0,10th-ASTH-CSLA,1,427,20200814198,Rossmore-SW-WE,-33.925766,150.769163,3804.08919,10th-ASTH-CSLA
1,10th-ASTH-CSLA,1,427,20200814202,Rossmore-SE-WE,-33.929035,150.784891,5446.92407,10th-ASTH-CSLA
2,10th-ASTH-CSLA,1,427,20200814210,Austral-SW-WE,-33.931200,150.798671,6743.77943,10th-ASTH-CSLA
3,10th-ASTH-CSLA,1,427,20200814214,Austral-SE-WE,-33.933048,150.811829,7977.77206,10th-ASTH-CSLA
4,10th-ASTH-CSLA,1,427,20200814260,10thAv_AerotropolisSouth_b,-33.934483,150.740965,47.94503,10th-ASTH-CSLA

In [21]:
stops_tways = stopsseparate.loc[(stopsseparate['shape_id'].str.contains('Austral')==False) & (stopsseparate['shape_id'].str.contains('Rossmore')==False) & (stopsseparate['shape_id'].str.contains('KempsCreek')==False)]
stops_fromroutes = stopsseparate.loc[stopsseparate['shape_id'].str.contains('-from')]
stops_toroutes = stopsseparate.loc[stopsseparate['shape_id'].str.contains('-to')]
print(len(stops_tways))
print(len(stops_fromroutes))
print(len(stops_toroutes))

220
497
499

In [22]:
stops_tways['shape_id'].unique()

array(['10th-ASTH-CSLA', '10th-CSLA-ASTH', '15th-AERO-LVPL',
       '15th-LVPL-AERO', '20th-AERO-LVPL', '20th-LVPL-AERO',
       '25th-BPRK-CBMT', '25th-CBMT-BPRK', 'AERO-MG', 'B-AERO-BPRK',
       'B-BPRK-AERO', 'C-STCK-STMR', 'C-STMR-STCK', 'D-MTDT-RSMR',
       'D-RSMR-MTDT', 'E-BPRK-LPTN', 'E-LPTN-BPRK', 'MG-AERO'],
      dtype=object)

#### Add to_route length to from_route stop distances to combine to and from routes into one route

In [23]:
print(len(stops_fromroutes))
stops_fromroutes = stops_fromroutes.merge(parentroutes, how='left', on='parent_route')
print(len(stops_fromroutes))
stops_fromroutes.head()

497
497

,shape_id,begin,end,stop_id,stop_name,stop_lat,stop_lon,distAlongR,parent_route,toroute_length
0,Austral-NE-E-from,1,249,202008145,Austral-NE-3a,-33.915365,150.810117,628.95274,Austral-NE-E,14472.618325
1,Austral-NE-E-from,1,249,202008147,Austral-NE-4a,-33.914947,150.813379,1179.83625,Austral-NE-E,14472.618325
2,Austral-NE-E-from,1,249,202008149,Austral-NE-5a,-33.914784,150.817910,1673.45453,Austral-NE-E,14472.618325
3,Austral-NE-E-from,1,249,2020081411,Austral-NE-6a,-33.916636,150.819890,2057.65022,Austral-NE-E,14472.618325
4,Austral-NE-E-from,1,249,20200814242,15thAv_LiverpoolStation_b,-33.923103,150.926832,13073.60744,Austral-NE-E,14472.618325

In [24]:
stops_fromroutes.isnull().sum()

shape_id          0
begin             0
end               0
stop_id           0
stop_name         0
stop_lat          0
stop_lon          0
distAlongR        0
parent_route      0
toroute_length    0
dtype: int64

In [25]:
stops_fromroutes['distAlongR'].sum() + stops_fromroutes['toroute_length'].sum()

10643320.94622454

In [26]:
stops_fromroutes['distAlongR'] = stops_fromroutes['distAlongR']+stops_fromroutes['toroute_length']
stops_fromroutes['distAlongR'].sum()

10643320.94622454

In [27]:
stops_fromroutes = stops_fromroutes.drop('toroute_length', axis=1)
stops_fromroutes.head()

,shape_id,begin,end,stop_id,stop_name,stop_lat,stop_lon,distAlongR,parent_route
0,Austral-NE-E-from,1,249,202008145,Austral-NE-3a,-33.915365,150.810117,15101.571065,Austral-NE-E
1,Austral-NE-E-from,1,249,202008147,Austral-NE-4a,-33.914947,150.813379,15652.454575,Austral-NE-E
2,Austral-NE-E-from,1,249,202008149,Austral-NE-5a,-33.914784,150.817910,16146.072855,Austral-NE-E
3,Austral-NE-E-from,1,249,2020081411,Austral-NE-6a,-33.916636,150.819890,16530.268545,Austral-NE-E
4,Austral-NE-E-from,1,249,20200814242,15thAv_LiverpoolStation_b,-33.923103,150.926832,27546.225765,Austral-NE-E

### Merge tway stops, from route and to route stops, and generate stops.txt

In [28]:
(stops_tways['shape_id']!=stops_tways['parent_route']).sum()

0

In [29]:
# StopsByRoute for stoptimes
stops = stops_tways.append(stops_toroutes).append(stops_fromroutes).sort_values(['parent_route','distAlongR'])
stops.to_csv('StopsByRoute_TwaysAndLocalRoutes_TOD14.csv', index=False)

In [30]:
# stops.txt
stops['stop_id'] = stops['stop_id'].astype(str)
stops['stop_code'] = stops['stop_id'].astype(float)
stops['wheelchair_boarding'] = "0"
stops['location_type'] = ""
stops['parent_station'] = ""
stops['platform_code'] = ""
stops = stops[['stop_id','stop_code','stop_name','stop_lat','stop_lon','location_type','parent_station','wheelchair_boarding','platform_code']]
stops.head()

,stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,platform_code
4,20200814260,2.020081e+10,10thAv_AerotropolisSouth_b,-33.934483,150.740965,,,0,
0,20200814198,2.020081e+10,Rossmore-SW-WE,-33.925766,150.769163,,,0,
1,20200814202,2.020081e+10,Rossmore-SE-WE,-33.929035,150.784891,,,0,
2,20200814210,2.020081e+10,Austral-SW-WE,-33.931200,150.798671,,,0,
3,20200814214,2.020081e+10,Austral-SE-WE,-33.933048,150.811829,,,0,

In [31]:
len(stops)

1216

In [32]:
stops.to_csv('./output/future/optimalTODlocation/TOD1_4/stops.txt')